$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$root = (Get-Location).Path

$packagePath = Join-Path $root "package.json"
$zhPagePath = Join-Path $root "app\products\page.tsx"
$localePagePath = Join-Path $root "app\[locale]\products\page.tsx"

$requiredPaths = @(
  $packagePath,
  $zhPagePath,
  $localePagePath
)

foreach ($requiredPath in $requiredPaths) {
  if (-not (Test-Path -LiteralPath $requiredPath)) {
    throw "没有找到必要文件：$requiredPath"
  }
}

$stamp = Get-Date -Format "yyyyMMdd-HHmmss"
$backupMap = @{}
$createdFiles = New-Object System.Collections.Generic.List[string]

function Backup-File {
  param([string]$Path)

  if (-not (Test-Path -LiteralPath $Path)) {
    return
  }

  if ($script:backupMap.ContainsKey($Path)) {
    return
  }

  $backupPath = $Path + "." + $stamp + ".bak"
  Copy-Item -LiteralPath $Path -Destination $backupPath -Force
  $script:backupMap[$Path] = $backupPath
  Write-Host "已备份：$backupPath" -ForegroundColor Yellow
}

function Write-Utf8NoBom {
  param(
    [string]$Path,
    [string]$Content
  )

  $directory = Split-Path -Parent $Path

  if (-not (Test-Path -LiteralPath $directory)) {
    New-Item -ItemType Directory -Path $directory -Force | Out-Null
  }

  if (-not (Test-Path -LiteralPath $Path)) {
    $script:createdFiles.Add($Path)
  } else {
    Backup-File -Path $Path
  }

  $encoding = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($Path, $Content, $encoding)
}

function Decode-Base64Utf8 {
  param([string]$Encoded)

  $bytes = [System.Convert]::FromBase64String($Encoded)
  return [System.Text.Encoding]::UTF8.GetString($bytes)
}

function Ensure-SkeletonFallback {
  param(
    [string]$Path,
    [string]$LocaleExpression
  )

  $content = Get-Content -LiteralPath $Path -Raw -Encoding UTF8
  Backup-File -Path $Path

  if ($content -notmatch 'import\s+ProductPageSkeleton\s+from\s+["'']@/components/common/ProductPageSkeleton["'']') {
    $productImport = 'import ProductSelectionClient from "@/components/products/selection/ProductSelectionClient";'

    if (-not $content.Contains($productImport)) {
      throw "无法在页面中找到 ProductSelectionClient 引入：$Path"
    }

    $replacementImport = 'import ProductPageSkeleton from "@/components/common/ProductPageSkeleton";' + [Environment]::NewLine + $productImport
    $content = $content.Replace($productImport, $replacementImport)
  }

  if ($content -notmatch 'import\s+\{\s*Suspense\s*\}\s+from\s+["'']react["'']') {
    $firstImportIndex = $content.IndexOf("import ")

    if ($firstImportIndex -lt 0) {
      throw "无法在页面中找到 import 插入位置：$Path"
    }

    $content = $content.Insert(
      $firstImportIndex,
      'import { Suspense } from "react";' + [Environment]::NewLine + [Environment]::NewLine
    )
  }

  $content = [Regex]::Replace(
    $content,
    'fallback=\{\s*null\s*\}',
    'fallback={<ProductPageSkeleton variant="selection" />}'
  )

  if ($content -notmatch '<Suspense\b') {
    $clientPattern = 'return\s+<ProductSelectionClient\s+locale=\{' + [Regex]::Escape($LocaleExpression) + '\}\s*/>;'
    $clientStringPattern = 'return\s+<ProductSelectionClient\s+locale=["'']' + [Regex]::Escape($LocaleExpression) + '["'']\s*/>;'

    $replacement = @"
return (
    <Suspense fallback={<ProductPageSkeleton variant="selection" />}>
      <ProductSelectionClient locale={$LocaleExpression} />
    </Suspense>
  );
"@

    if ([Regex]::IsMatch($content, $clientPattern)) {
      $content = [Regex]::Replace($content, $clientPattern, $replacement.Trim(), 1)
    }
    elseif ([Regex]::IsMatch($content, $clientStringPattern)) {
      $stringReplacement = @"
return (
    <Suspense fallback={<ProductPageSkeleton variant="selection" />}>
      <ProductSelectionClient locale="$LocaleExpression" />
    </Suspense>
  );
"@

      $content = [Regex]::Replace(
        $content,
        $clientStringPattern,
        $stringReplacement.Trim(),
        1
      )
    }
    else {
      throw "无法在页面中找到 ProductSelectionClient 返回结构：$Path"
    }
  }

  $encoding = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($Path, $content, $encoding)
}

try {

  $content_1Base64 = @'
InVzZSBjbGllbnQiOwoKLyogPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09CiAgIFByb2R1Y3RQYWdlU2tlbGV0b24udHN4CiAgIOaBkuawuOi+vuWumOe9ke+9nOS6p+WTgeS4reW/g+S4juS6p+WTgeivpuaDhemhteWKoOi9vemqqOaetgoKICAg6K+05piO77yaCiAgIDEuIOmhtemdouWIh+aNouaXtuWFiOaYvuekuue7k+aehOWNoOS9jQogICAyLiDpmLLmraLmraPmlofkuLrnqbrml7YgRm9vdGVyIOaPkOWJjemhtuS4iuadpQogICAzLiBzZWxlY3Rpb24g55So5LqO5Lqn5ZOB5Lit5b+DCiAgIDQuIGRldGFpbCDnlKjkuo7kuqflk4Hor6bmg4XpobUKPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09ICovCgppbXBvcnQgc3R5bGVzIGZyb20gIi4vUHJvZHVjdFBhZ2VTa2VsZXRvbi5tb2R1bGUuY3NzIjsKCnR5cGUgUHJvZHVjdFBhZ2VTa2VsZXRvblByb3BzID0gewogIHZhcmlhbnQ6ICJzZWxlY3Rpb24iIHwgImRldGFpbCI7Cn07CgpmdW5jdGlvbiBTa2VsZXRvbkJsb2NrKHsKICBjbGFzc05hbWUgPSAiIiwKfTogewogIGNsYXNzTmFtZT86IHN0cmluZzsKfSkgewogIHJldHVybiAoCiAgICA8ZGl2CiAgICAgIGNsYXNzTmFtZT17W3N0eWxlcy5ibG9jaywgY2xhc3NOYW1lXQogICAgICAgIC5maWx0ZXIoQm9vbGVhbikKICAgICAgICAuam9pbigiICIpfQogICAgLz4KICApOwp9CgpleHBvcnQgZGVmYXVsdCBmdW5jdGlvbiBQcm9kdWN0UGFnZVNrZWxldG9uKHsKICB2YXJpYW50LAp9OiBQcm9kdWN0UGFnZVNrZWxldG9uUHJvcHMpIHsKICByZXR1cm4gKAogICAgPHNlY3Rpb24KICAgICAgY2xhc3NOYW1lPXtzdHlsZXMuc2hlbGx9CiAgICAgIGFyaWEtbGFiZWw9IumhtemdouWKoOi9veS4rSIKICAgICAgYXJpYS1idXN5PSJ0cnVlIgogICAgPgogICAgICA8ZGl2IGNsYXNzTmFtZT17c3R5bGVzLmJyZWFkY3J1bWJCYXJ9PgogICAgICAgIDxkaXYgY2xhc3NOYW1lPXtzdHlsZXMuY29udGFpbmVyfT4KICAgICAgICAgIDxTa2VsZXRvbkJsb2NrIGNsYXNzTmFtZT17c3R5bGVzLmJyZWFkY3J1bWJMaW5lfSAvPgogICAgICAgIDwvZGl2PgogICAgICA8L2Rpdj4KCiAgICAgIHt2YXJpYW50ID09PSAic2VsZWN0aW9uIiA/ICgKICAgICAgICA8PgogICAgICAgICAgPGRpdiBjbGFzc05hbWU9e3N0eWxlcy5zZWFyY2hCYW5kfT4KICAgICAgICAgICAgPFNrZWxldG9uQmxvY2sgY2xhc3NOYW1lPXtzdHlsZXMuc2VhcmNoQm94fSAvPgogICAgICAgICAgPC9kaXY+CgogICAgICAgICAgPGRpdiBjbGFzc05hbWU9e3N0eWxlcy5jb250YWluZXJ9PgogICAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT17c3R5bGVzLmNhdGVnb3J5VGFic30+CiAgICAgICAgICAgICAge0FycmF5LmZyb20oeyBsZW5ndGg6IDYgfSkubWFwKChfLCBpbmRleCkgPT4gKAogICAgICAgICAgICAgICAgPFNrZWxldG9uQmxvY2sKICAgICAgICAgICAgICAgICAga2V5PXtpbmRleH0KICAgICAgICAgICAgICAgICAgY2xhc3NOYW1lPXtzdHlsZXMuY2F0ZWdvcnlUYWJ9CiAgICAgICAgICAgICAgICAvPgogICAgICAgICAgICAgICkpfQogICAgICAgICAgICA8L2Rpdj4KCiAgICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPXtzdHlsZXMuc2VsZWN0aW9uTGF5b3V0fT4KICAgICAgICAgICAgICA8YXNpZGUgY2xhc3NOYW1lPXtzdHlsZXMuZmlsdGVyUGFuZWx9PgogICAgICAgICAgICAgICAgPFNrZWxldG9uQmxvY2sgY2xhc3NOYW1lPXtzdHlsZXMuZmlsdGVyVGl0bGV9IC8+CgogICAgICAgICAgICAgICAge0FycmF5LmZyb20oeyBsZW5ndGg6IDUgfSkubWFwKChfLCBpbmRleCkgPT4gKAogICAgICAgICAgICAgICAgICA8ZGl2CiAgICAgICAgICAgICAgICAgICAga2V5PXtpbmRleH0KICAgICAgICAgICAgICAgICAgICBjbGFzc05hbWU9e3N0eWxlcy5maWx0ZXJHcm91cH0KICAgICAgICAgICAgICAgICAgPgogICAgICAgICAgICAgICAgICAgIDxTa2VsZXRvbkJsb2NrIGNsYXNzTmFtZT17c3R5bGVzLmZpbHRlckxhYmVsfSAvPgogICAgICAgICAgICAgICAgICAgIDxTa2VsZXRvbkJsb2NrIGNsYXNzTmFtZT17c3R5bGVzLmZpbHRlck9wdGlvbn0gLz4KICAgICAgICAgICAgICAgICAgICA8U2tlbGV0b25CbG9jayBjbGFzc05hbWU9e3N0eWxlcy5maWx0ZXJPcHRpb25TaG9ydH0gLz4KICAgICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICApKX0KICAgICAgICAgICAgICA8L2FzaWRlPgoKICAgICAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT17c3R5bGVzLnNlbGVjdGlvbk1haW59PgogICAgICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9e3N0eWxlcy50b29sYmFyfT4KICAgICAgICAgICAgICAgICAgPFNrZWxldG9uQmxvY2sgY2xhc3NOYW1lPXtzdHlsZXMudG9vbGJhclRpdGxlfSAvPgogICAgICAgICAgICAgICAgICA8U2tlbGV0b25CbG9jayBjbGFzc05hbWU9e3N0eWxlcy50b29sYmFyQnV0dG9ufSAvPgogICAgICAgICAgICAgICAgPC9kaXY+CgogICAgICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9e3N0eWxlcy5jYXJkR3JpZH0+CiAgICAgICAgICAgICAgICAgIHtBcnJheS5mcm9tKHsgbGVuZ3RoOiA4IH0pLm1hcCgoXywgaW5kZXgpID0+ICgKICAgICAgICAgICAgICAgICAgICA8YXJ0aWNsZQogICAgICAgICAgICAgICAgICAgICAga2V5PXtpbmRleH0KICAgICAgICAgICAgICAgICAgICAgIGNsYXNzTmFtZT17c3R5bGVzLnByb2R1Y3RDYXJkfQogICAgICAgICAgICAgICAgICAgID4KICAgICAgICAgICAgICAgICAgICAgIDxTa2VsZXRvbkJsb2NrIGNsYXNzTmFtZT17c3R5bGVzLmNhcmRJbWFnZX0gLz4KICAgICAgICAgICAgICAgICAgICAgIDxTa2VsZXRvbkJsb2NrIGNsYXNzTmFtZT17c3R5bGVzLmNhcmRUaXRsZX0gLz4KICAgICAgICAgICAgICAgICAgICAgIDxTa2VsZXRvbkJsb2NrIGNsYXNzTmFtZT17c3R5bGVzLmNhcmRNZXRhfSAvPgogICAgICAgICAgICAgICAgICAgICAgPFNrZWxldG9uQmxvY2sgY2xhc3NOYW1lPXtzdHlsZXMuY2FyZEJ1dHRvbn0gLz4KICAgICAgICAgICAgICAgICAgICA8L2FydGljbGU+CiAgICAgICAgICAgICAgICAgICkpfQogICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgPC9kaXY+CiAgICAgICAgPC8+CiAgICAgICkgOiAoCiAgICAgICAgPGRpdiBjbGFzc05hbWU9e3N0eWxlcy5jb250YWluZXJ9PgogICAgICAgICAgPGRpdiBjbGFzc05hbWU9e3N0eWxlcy5kZXRhaWxIZXJvfT4KICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9e3N0eWxlcy5kZXRhaWxNZWRpYX0+CiAgICAgICAgICAgICAgPFNrZWxldG9uQmxvY2sgY2xhc3NOYW1lPXtzdHlsZXMuZGV0YWlsSW1hZ2V9IC8+CgogICAgICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPXtzdHlsZXMudGh1bWJuYWlsUm93fT4KICAgICAgICAgICAgICAgIHtBcnJheS5mcm9tKHsgbGVuZ3RoOiA0IH0pLm1hcCgoXywgaW5kZXgpID0+ICgKICAgICAgICAgICAgICAgICAgPFNrZWxldG9uQmxvY2sKICAgICAgICAgICAgICAgICAgICBrZXk9e2luZGV4fQogICAgICAgICAgICAgICAgICAgIGNsYXNzTmFtZT17c3R5bGVzLnRodW1ibmFpbH0KICAgICAgICAgICAgICAgICAgLz4KICAgICAgICAgICAgICAgICkpfQogICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICA8L2Rpdj4KCiAgICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPXtzdHlsZXMuZGV0YWlsSW5mb30+CiAgICAgICAgICAgICAgPFNrZWxldG9uQmxvY2sgY2xhc3NOYW1lPXtzdHlsZXMuZGV0YWlsRXllYnJvd30gLz4KICAgICAgICAgICAgICA8U2tlbGV0b25CbG9jayBjbGFzc05hbWU9e3N0eWxlcy5kZXRhaWxUaXRsZX0gLz4KICAgICAgICAgICAgICA8U2tlbGV0b25CbG9jayBjbGFzc05hbWU9e3N0eWxlcy5kZXRhaWxUaXRsZVNob3J0fSAvPgoKICAgICAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT17c3R5bGVzLmRldGFpbFRleHRHcm91cH0+CiAgICAgICAgICAgICAgICA8U2tlbGV0b25CbG9jayBjbGFzc05hbWU9e3N0eWxlcy5kZXRhaWxUZXh0fSAvPgogICAgICAgICAgICAgICAgPFNrZWxldG9uQmxvY2sgY2xhc3NOYW1lPXtzdHlsZXMuZGV0YWlsVGV4dH0gLz4KICAgICAgICAgICAgICAgIDxTa2VsZXRvbkJsb2NrIGNsYXNzTmFtZT17c3R5bGVzLmRldGFpbFRleHRTaG9ydH0gLz4KICAgICAgICAgICAgICA8L2Rpdj4KCiAgICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9e3N0eWxlcy5kZXRhaWxNb2RlbFJvd30+CiAgICAgICAgICAgICAgICA8U2tlbGV0b25CbG9jayBjbGFzc05hbWU9e3N0eWxlcy5kZXRhaWxNb2RlbH0gLz4KICAgICAgICAgICAgICAgIDxTa2VsZXRvbkJsb2NrIGNsYXNzTmFtZT17c3R5bGVzLmRldGFpbENvbmZpZ0J1dHRvbn0gLz4KICAgICAgICAgICAgICA8L2Rpdj4KCiAgICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9e3N0eWxlcy5kZXRhaWxBY3Rpb25Sb3d9PgogICAgICAgICAgICAgICAgPFNrZWxldG9uQmxvY2sgY2xhc3NOYW1lPXtzdHlsZXMuZGV0YWlsQWN0aW9ufSAvPgogICAgICAgICAgICAgICAgPFNrZWxldG9uQmxvY2sgY2xhc3NOYW1lPXtzdHlsZXMuZGV0YWlsQWN0aW9ufSAvPgogICAgICAgICAgICAgICAgPFNrZWxldG9uQmxvY2sgY2xhc3NOYW1lPXtzdHlsZXMuZGV0YWlsQWN0aW9uV2lkZX0gLz4KICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICA8L2Rpdj4KCiAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT17c3R5bGVzLmRldGFpbFRhYnN9PgogICAgICAgICAgICB7QXJyYXkuZnJvbSh7IGxlbmd0aDogNCB9KS5tYXAoKF8sIGluZGV4KSA9PiAoCiAgICAgICAgICAgICAgPFNrZWxldG9uQmxvY2sKICAgICAgICAgICAgICAgIGtleT17aW5kZXh9CiAgICAgICAgICAgICAgICBjbGFzc05hbWU9e3N0eWxlcy5kZXRhaWxUYWJ9CiAgICAgICAgICAgICAgLz4KICAgICAgICAgICAgKSl9CiAgICAgICAgICA8L2Rpdj4KCiAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT17c3R5bGVzLmRldGFpbFBhbmVsfT4KICAgICAgICAgICAgPFNrZWxldG9uQmxvY2sgY2xhc3NOYW1lPXtzdHlsZXMucGFuZWxIZWFkaW5nfSAvPgoKICAgICAgICAgICAge0FycmF5LmZyb20oeyBsZW5ndGg6IDYgfSkubWFwKChfLCBpbmRleCkgPT4gKAogICAgICAgICAgICAgIDxkaXYKICAgICAgICAgICAgICAgIGtleT17aW5kZXh9CiAgICAgICAgICAgICAgICBjbGFzc05hbWU9e3N0eWxlcy5zcGVjUm93fQogICAgICAgICAgICAgID4KICAgICAgICAgICAgICAgIDxTa2VsZXRvbkJsb2NrIGNsYXNzTmFtZT17c3R5bGVzLnNwZWNMYWJlbH0gLz4KICAgICAgICAgICAgICAgIDxTa2VsZXRvbkJsb2NrIGNsYXNzTmFtZT17c3R5bGVzLnNwZWNWYWx1ZX0gLz4KICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgKSl9CiAgICAgICAgICA8L2Rpdj4KICAgICAgICA8L2Rpdj4KICAgICAgKX0KICAgIDwvc2VjdGlvbj4KICApOwp9Cg==
'@
  $content_1 = Decode-Base64Utf8 -Encoded ($content_1Base64.Trim())
  Write-Utf8NoBom -Path (Join-Path $root "components\\common\\ProductPageSkeleton.tsx") -Content $content_1

  $content_2Base64 = @'
LyogPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09CiAgIFByb2R1Y3RQYWdlU2tlbGV0b24ubW9kdWxlLmNzcwogICDmgZLmsLjovr7lrpjnvZHvvZzkuqflk4HkuK3lv4PkuI7kuqflk4Hor6bmg4XpobXliqDovb3pqqjmnrYKPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09ICovCgouc2hlbGwgewogIHdpZHRoOiAxMDAlOwogIG1pbi13aWR0aDogMDsKICBtaW4taGVpZ2h0OiA5MDBweDsKICBwYWRkaW5nLXRvcDogODJweDsKICBiYWNrZ3JvdW5kOiAjZmZmZmZmOwp9CgouY29udGFpbmVyIHsKICB3aWR0aDogbWluKDE2MDBweCwgY2FsYygxMDAlIC0gNDhweCkpOwogIG1hcmdpbjogMCBhdXRvOwp9CgouYmxvY2sgewogIHBvc2l0aW9uOiByZWxhdGl2ZTsKICBvdmVyZmxvdzogaGlkZGVuOwogIGJhY2tncm91bmQ6ICNlZGYxZjY7Cn0KCi5ibG9jazo6YWZ0ZXIgewogIGNvbnRlbnQ6ICIiOwogIHBvc2l0aW9uOiBhYnNvbHV0ZTsKICBpbnNldDogMDsKICB0cmFuc2Zvcm06IHRyYW5zbGF0ZVgoLTEwMCUpOwogIGJhY2tncm91bmQ6IGxpbmVhci1ncmFkaWVudCgKICAgIDkwZGVnLAogICAgdHJhbnNwYXJlbnQgMCUsCiAgICByZ2JhKDI1NSwgMjU1LCAyNTUsIDAuNzIpIDUwJSwKICAgIHRyYW5zcGFyZW50IDEwMCUKICApOwogIGFuaW1hdGlvbjogcHJvZHVjdFNrZWxldG9uU2hpbW1lciAxLjRzIGVhc2UtaW4tb3V0IGluZmluaXRlOwp9CgpAa2V5ZnJhbWVzIHByb2R1Y3RTa2VsZXRvblNoaW1tZXIgewogIDEwMCUgewogICAgdHJhbnNmb3JtOiB0cmFuc2xhdGVYKDEwMCUpOwogIH0KfQoKLmJyZWFkY3J1bWJCYXIgewogIGJvcmRlci1ib3R0b206IDFweCBzb2xpZCByZ2JhKDIzLCA1MSwgMTA0LCAwLjE0KTsKICBiYWNrZ3JvdW5kOiAjZmZmZmZmOwp9CgouYnJlYWRjcnVtYkxpbmUgewogIHdpZHRoOiAyMTBweDsKICBoZWlnaHQ6IDE4cHg7CiAgbWFyZ2luOiAyOHB4IDAgMThweDsKfQoKLnNlYXJjaEJhbmQgewogIGRpc3BsYXk6IGZsZXg7CiAgbWluLWhlaWdodDogOTBweDsKICBhbGlnbi1pdGVtczogY2VudGVyOwogIGp1c3RpZnktY29udGVudDogY2VudGVyOwogIGJvcmRlci1ib3R0b206IDFweCBzb2xpZCByZ2JhKDIzLCA1MSwgMTA0LCAwLjEpOwogIGJhY2tncm91bmQ6ICNmNGY3ZmI7Cn0KCi5zZWFyY2hCb3ggewogIHdpZHRoOiBtaW4oNzYwcHgsIGNhbGMoMTAwJSAtIDMycHgpKTsKICBoZWlnaHQ6IDQ2cHg7Cn0KCi5jYXRlZ29yeVRhYnMgewogIGRpc3BsYXk6IGdyaWQ7CiAgZ3JpZC10ZW1wbGF0ZS1jb2x1bW5zOiByZXBlYXQoNiwgbWlubWF4KDAsIDFmcikpOwogIGdhcDogMTJweDsKICBtYXJnaW46IDI4cHggMCAyNHB4Owp9CgouY2F0ZWdvcnlUYWIgewogIGhlaWdodDogNDZweDsKfQoKLnNlbGVjdGlvbkxheW91dCB7CiAgZGlzcGxheTogZ3JpZDsKICBncmlkLXRlbXBsYXRlLWNvbHVtbnM6IDI2MHB4IG1pbm1heCgwLCAxZnIpOwogIGdhcDogMjhweDsKICBhbGlnbi1pdGVtczogc3RhcnQ7CiAgcGFkZGluZy1ib3R0b206IDgwcHg7Cn0KCi5maWx0ZXJQYW5lbCB7CiAgbWluLWhlaWdodDogNjIwcHg7CiAgcGFkZGluZzogMjJweCAxOHB4OwogIGJvcmRlcjogMXB4IHNvbGlkIHJnYmEoMjMsIDUxLCAxMDQsIDAuMTQpOwp9CgouZmlsdGVyVGl0bGUgewogIHdpZHRoOiA1NCU7CiAgaGVpZ2h0OiAyMnB4OwogIG1hcmdpbi1ib3R0b206IDI4cHg7Cn0KCi5maWx0ZXJHcm91cCB7CiAgcGFkZGluZzogMThweCAwOwogIGJvcmRlci10b3A6IDFweCBzb2xpZCByZ2JhKDIzLCA1MSwgMTA0LCAwLjEpOwp9CgouZmlsdGVyTGFiZWwgewogIHdpZHRoOiA0MiU7CiAgaGVpZ2h0OiAxNnB4OwogIG1hcmdpbi1ib3R0b206IDE2cHg7Cn0KCi5maWx0ZXJPcHRpb24gewogIHdpZHRoOiA4NiU7CiAgaGVpZ2h0OiAxNHB4OwogIG1hcmdpbi1ib3R0b206IDEycHg7Cn0KCi5maWx0ZXJPcHRpb25TaG9ydCB7CiAgd2lkdGg6IDY0JTsKICBoZWlnaHQ6IDE0cHg7Cn0KCi5zZWxlY3Rpb25NYWluIHsKICBtaW4td2lkdGg6IDA7Cn0KCi50b29sYmFyIHsKICBkaXNwbGF5OiBmbGV4OwogIG1pbi1oZWlnaHQ6IDQ2cHg7CiAgbWFyZ2luLWJvdHRvbTogMThweDsKICBhbGlnbi1pdGVtczogY2VudGVyOwogIGp1c3RpZnktY29udGVudDogc3BhY2UtYmV0d2VlbjsKICBnYXA6IDIwcHg7Cn0KCi50b29sYmFyVGl0bGUgewogIHdpZHRoOiAyMjBweDsKICBoZWlnaHQ6IDIwcHg7Cn0KCi50b29sYmFyQnV0dG9uIHsKICB3aWR0aDogMTA4cHg7CiAgaGVpZ2h0OiAzNnB4Owp9CgouY2FyZEdyaWQgewogIGRpc3BsYXk6IGdyaWQ7CiAgZ3JpZC10ZW1wbGF0ZS1jb2x1bW5zOiByZXBlYXQoNCwgbWlubWF4KDAsIDFmcikpOwogIGdhcDogMThweDsKfQoKLnByb2R1Y3RDYXJkIHsKICBtaW4td2lkdGg6IDA7CiAgcGFkZGluZzogMTRweCAxNHB4IDE2cHg7CiAgYm9yZGVyOiAxcHggc29saWQgcmdiYSgyMywgNTEsIDEwNCwgMC4xNCk7CiAgYmFja2dyb3VuZDogI2ZmZmZmZjsKfQoKLmNhcmRJbWFnZSB7CiAgd2lkdGg6IDEwMCU7CiAgYXNwZWN0LXJhdGlvOiAxIC8gMTsKICBtYXJnaW4tYm90dG9tOiAxNnB4Owp9CgouY2FyZFRpdGxlIHsKICB3aWR0aDogNzIlOwogIGhlaWdodDogMjBweDsKICBtYXJnaW4tYm90dG9tOiAxMnB4Owp9CgouY2FyZE1ldGEgewogIHdpZHRoOiA4OCU7CiAgaGVpZ2h0OiAxNHB4OwogIG1hcmdpbi1ib3R0b206IDE4cHg7Cn0KCi5jYXJkQnV0dG9uIHsKICB3aWR0aDogMTAwJTsKICBoZWlnaHQ6IDM4cHg7Cn0KCi5kZXRhaWxIZXJvIHsKICBkaXNwbGF5OiBncmlkOwogIGdyaWQtdGVtcGxhdGUtY29sdW1uczogbWlubWF4KDAsIDEuMTRmcikgbWlubWF4KDM4MHB4LCAwLjg2ZnIpOwogIGdhcDogNTZweDsKICBwYWRkaW5nOiA0MHB4IDAgNDhweDsKfQoKLmRldGFpbE1lZGlhLAouZGV0YWlsSW5mbyB7CiAgbWluLXdpZHRoOiAwOwp9CgouZGV0YWlsSW1hZ2UgewogIHdpZHRoOiAxMDAlOwogIG1pbi1oZWlnaHQ6IDUyMHB4Owp9CgoudGh1bWJuYWlsUm93IHsKICBkaXNwbGF5OiBmbGV4OwogIGdhcDogMTRweDsKICBtYXJnaW4tdG9wOiAxNHB4Owp9CgoudGh1bWJuYWlsIHsKICB3aWR0aDogODJweDsKICBoZWlnaHQ6IDgycHg7Cn0KCi5kZXRhaWxJbmZvIHsKICBwYWRkaW5nLXRvcDogMTBweDsKfQoKLmRldGFpbEV5ZWJyb3cgewogIHdpZHRoOiAxMjBweDsKICBoZWlnaHQ6IDE2cHg7CiAgbWFyZ2luLWJvdHRvbTogMThweDsKfQoKLmRldGFpbFRpdGxlIHsKICB3aWR0aDogODIlOwogIGhlaWdodDogMzRweDsKICBtYXJnaW4tYm90dG9tOiAxMnB4Owp9CgouZGV0YWlsVGl0bGVTaG9ydCB7CiAgd2lkdGg6IDU2JTsKICBoZWlnaHQ6IDM0cHg7CiAgbWFyZ2luLWJvdHRvbTogMzRweDsKfQoKLmRldGFpbFRleHRHcm91cCB7CiAgZGlzcGxheTogZ3JpZDsKICBnYXA6IDEycHg7CiAgbWFyZ2luLWJvdHRvbTogMzRweDsKfQoKLmRldGFpbFRleHQgewogIHdpZHRoOiAxMDAlOwogIGhlaWdodDogMTZweDsKfQoKLmRldGFpbFRleHRTaG9ydCB7CiAgd2lkdGg6IDc0JTsKICBoZWlnaHQ6IDE2cHg7Cn0KCi5kZXRhaWxNb2RlbFJvdyB7CiAgZGlzcGxheTogZ3JpZDsKICBncmlkLXRlbXBsYXRlLWNvbHVtbnM6IG1pbm1heCgwLCAxZnIpIDEyNnB4OwogIGdhcDogMTJweDsKICBtYXJnaW4tYm90dG9tOiAxOHB4Owp9CgouZGV0YWlsTW9kZWwsCi5kZXRhaWxDb25maWdCdXR0b24gewogIGhlaWdodDogNDRweDsKfQoKLmRldGFpbEFjdGlvblJvdyB7CiAgZGlzcGxheTogZ3JpZDsKICBncmlkLXRlbXBsYXRlLWNvbHVtbnM6IDFmciAxZnIgMS4yNWZyOwogIGdhcDogMTBweDsKfQoKLmRldGFpbEFjdGlvbiwKLmRldGFpbEFjdGlvbldpZGUgewogIGhlaWdodDogNDJweDsKfQoKLmRldGFpbFRhYnMgewogIGRpc3BsYXk6IGdyaWQ7CiAgZ3JpZC10ZW1wbGF0ZS1jb2x1bW5zOiByZXBlYXQoNCwgbWlubWF4KDAsIDFmcikpOwogIGJvcmRlci10b3A6IDFweCBzb2xpZCByZ2JhKDIzLCA1MSwgMTA0LCAwLjE0KTsKICBib3JkZXItYm90dG9tOiAxcHggc29saWQgcmdiYSgyMywgNTEsIDEwNCwgMC4xNCk7Cn0KCi5kZXRhaWxUYWIgewogIGhlaWdodDogNThweDsKICBib3JkZXItcmlnaHQ6IDFweCBzb2xpZCAjZmZmZmZmOwp9CgouZGV0YWlsUGFuZWwgewogIG1pbi1oZWlnaHQ6IDQyMHB4OwogIHBhZGRpbmc6IDM0cHggMCA4MHB4Owp9CgoucGFuZWxIZWFkaW5nIHsKICB3aWR0aDogMTgwcHg7CiAgaGVpZ2h0OiAyNHB4OwogIG1hcmdpbi1ib3R0b206IDIycHg7Cn0KCi5zcGVjUm93IHsKICBkaXNwbGF5OiBncmlkOwogIGdyaWQtdGVtcGxhdGUtY29sdW1uczogMzQlIG1pbm1heCgwLCAxZnIpOwogIG1pbi1oZWlnaHQ6IDUycHg7CiAgYm9yZGVyLXRvcDogMXB4IHNvbGlkIHJnYmEoMjMsIDUxLCAxMDQsIDAuMSk7CiAgYWxpZ24taXRlbXM6IGNlbnRlcjsKfQoKLnNwZWNMYWJlbCB7CiAgd2lkdGg6IDYyJTsKICBoZWlnaHQ6IDE1cHg7Cn0KCi5zcGVjVmFsdWUgewogIHdpZHRoOiA1NCU7CiAgaGVpZ2h0OiAxNXB4Owp9CgpAbWVkaWEgKG1heC13aWR0aDogMTI4MHB4KSB7CiAgLmNhcmRHcmlkIHsKICAgIGdyaWQtdGVtcGxhdGUtY29sdW1uczogcmVwZWF0KDMsIG1pbm1heCgwLCAxZnIpKTsKICB9CgogIC5kZXRhaWxIZXJvIHsKICAgIGdhcDogMzZweDsKICB9Cn0KCkBtZWRpYSAobWF4LXdpZHRoOiA5MDBweCkgewogIC5zaGVsbCB7CiAgICBtaW4taGVpZ2h0OiA3NjBweDsKICAgIHBhZGRpbmctdG9wOiA3MHB4OwogIH0KCiAgLmNvbnRhaW5lciB7CiAgICB3aWR0aDogbWluKDEwMCUsIGNhbGMoMTAwJSAtIDMycHgpKTsKICB9CgogIC5icmVhZGNydW1iTGluZSB7CiAgICBtYXJnaW4tdG9wOiAxOHB4OwogIH0KCiAgLmNhdGVnb3J5VGFicyB7CiAgICBncmlkLXRlbXBsYXRlLWNvbHVtbnM6IHJlcGVhdCgzLCBtaW5tYXgoMCwgMWZyKSk7CiAgfQoKICAuc2VsZWN0aW9uTGF5b3V0IHsKICAgIGdyaWQtdGVtcGxhdGUtY29sdW1uczogMjIwcHggbWlubWF4KDAsIDFmcik7CiAgICBnYXA6IDIwcHg7CiAgfQoKICAuY2FyZEdyaWQgewogICAgZ3JpZC10ZW1wbGF0ZS1jb2x1bW5zOiByZXBlYXQoMiwgbWlubWF4KDAsIDFmcikpOwogIH0KCiAgLmRldGFpbEhlcm8gewogICAgZ3JpZC10ZW1wbGF0ZS1jb2x1bW5zOiAxZnI7CiAgfQoKICAuZGV0YWlsSW1hZ2UgewogICAgbWluLWhlaWdodDogNDYwcHg7CiAgfQp9CgpAbWVkaWEgKG1heC13aWR0aDogNjgwcHgpIHsKICAuc2hlbGwgewogICAgbWluLWhlaWdodDogNjgwcHg7CiAgfQoKICAuY29udGFpbmVyIHsKICAgIHdpZHRoOiBjYWxjKDEwMCUgLSAyNHB4KTsKICB9CgogIC5icmVhZGNydW1iTGluZSB7CiAgICB3aWR0aDogMTUwcHg7CiAgICBoZWlnaHQ6IDE1cHg7CiAgICBtYXJnaW46IDEycHggMCAxNHB4OwogIH0KCiAgLnNlYXJjaEJhbmQgewogICAgbWluLWhlaWdodDogODJweDsKICB9CgogIC5zZWFyY2hCb3ggewogICAgd2lkdGg6IGNhbGMoMTAwJSAtIDI0cHgpOwogICAgaGVpZ2h0OiA0NHB4OwogIH0KCiAgLmNhdGVnb3J5VGFicyB7CiAgICBncmlkLXRlbXBsYXRlLWNvbHVtbnM6IHJlcGVhdCgzLCBtaW5tYXgoMCwgMWZyKSk7CiAgICBnYXA6IDhweDsKICAgIG1hcmdpbjogMThweCAwOwogIH0KCiAgLmNhdGVnb3J5VGFiIHsKICAgIGhlaWdodDogNDBweDsKICB9CgogIC5zZWxlY3Rpb25MYXlvdXQgewogICAgZGlzcGxheTogYmxvY2s7CiAgICBwYWRkaW5nLWJvdHRvbTogNDhweDsKICB9CgogIC5maWx0ZXJQYW5lbCB7CiAgICBtaW4taGVpZ2h0OiAxNzBweDsKICAgIG1hcmdpbi1ib3R0b206IDE4cHg7CiAgICBwYWRkaW5nOiAxNnB4IDE0cHg7CiAgfQoKICAuZmlsdGVyR3JvdXA6bnRoLW9mLXR5cGUobiArIDMpIHsKICAgIGRpc3BsYXk6IG5vbmU7CiAgfQoKICAudG9vbGJhciB7CiAgICBtYXJnaW4tYm90dG9tOiAxNHB4OwogIH0KCiAgLnRvb2xiYXJUaXRsZSB7CiAgICB3aWR0aDogMTYwcHg7CiAgfQoKICAuY2FyZEdyaWQgewogICAgZ3JpZC10ZW1wbGF0ZS1jb2x1bW5zOiByZXBlYXQoMiwgbWlubWF4KDAsIDFmcikpOwogICAgZ2FwOiAxMHB4OwogIH0KCiAgLnByb2R1Y3RDYXJkIHsKICAgIHBhZGRpbmc6IDhweCA4cHggMTJweDsKICB9CgogIC5jYXJkSW1hZ2UgewogICAgbWFyZ2luLWJvdHRvbTogMTJweDsKICB9CgogIC5jYXJkR3JpZCAucHJvZHVjdENhcmQ6bnRoLWNoaWxkKG4gKyA3KSB7CiAgICBkaXNwbGF5OiBub25lOwogIH0KCiAgLmRldGFpbEhlcm8gewogICAgZ2FwOiAyNnB4OwogICAgcGFkZGluZzogMjJweCAwIDM0cHg7CiAgfQoKICAuZGV0YWlsSW1hZ2UgewogICAgbWluLWhlaWdodDogMzYwcHg7CiAgfQoKICAudGh1bWJuYWlsIHsKICAgIHdpZHRoOiA2NnB4OwogICAgaGVpZ2h0OiA2NnB4OwogIH0KCiAgLmRldGFpbEluZm8gewogICAgcGFkZGluZy10b3A6IDA7CiAgfQoKICAuZGV0YWlsVGl0bGUsCiAgLmRldGFpbFRpdGxlU2hvcnQgewogICAgaGVpZ2h0OiAyOHB4OwogIH0KCiAgLmRldGFpbE1vZGVsUm93IHsKICAgIGdyaWQtdGVtcGxhdGUtY29sdW1uczogbWlubWF4KDAsIDFmcikgMTA2cHg7CiAgfQoKICAuZGV0YWlsQWN0aW9uUm93IHsKICAgIGdyaWQtdGVtcGxhdGUtY29sdW1uczogMWZyIDFmcjsKICB9CgogIC5kZXRhaWxBY3Rpb25XaWRlIHsKICAgIGdyaWQtY29sdW1uOiAxIC8gLTE7CiAgfQoKICAuZGV0YWlsVGFicyB7CiAgICBncmlkLXRlbXBsYXRlLWNvbHVtbnM6IHJlcGVhdCg0LCBtaW5tYXgoOTJweCwgMWZyKSk7CiAgICBvdmVyZmxvdy14OiBhdXRvOwogIH0KCiAgLmRldGFpbFBhbmVsIHsKICAgIG1pbi1oZWlnaHQ6IDM0MHB4OwogICAgcGFkZGluZy1ib3R0b206IDQ4cHg7CiAgfQoKICAuc3BlY1JvdyB7CiAgICBncmlkLXRlbXBsYXRlLWNvbHVtbnM6IDQwJSBtaW5tYXgoMCwgMWZyKTsKICB9Cn0KCkBtZWRpYSAocHJlZmVycy1yZWR1Y2VkLW1vdGlvbjogcmVkdWNlKSB7CiAgLmJsb2NrOjphZnRlciB7CiAgICBhbmltYXRpb246IG5vbmU7CiAgfQp9Cg==
'@
  $content_2 = Decode-Base64Utf8 -Encoded ($content_2Base64.Trim())
  Write-Utf8NoBom -Path (Join-Path $root "components\\common\\ProductPageSkeleton.module.css") -Content $content_2

  $content_3Base64 = @'
aW1wb3J0IFByb2R1Y3RQYWdlU2tlbGV0b24gZnJvbSAiQC9jb21wb25lbnRzL2NvbW1vbi9Qcm9kdWN0UGFnZVNrZWxldG9uIjsKCmV4cG9ydCBkZWZhdWx0IGZ1bmN0aW9uIFByb2R1Y3RzTG9hZGluZygpIHsKICByZXR1cm4gPFByb2R1Y3RQYWdlU2tlbGV0b24gdmFyaWFudD0ic2VsZWN0aW9uIiAvPjsKfQo=
'@
  $content_3 = Decode-Base64Utf8 -Encoded ($content_3Base64.Trim())
  Write-Utf8NoBom -Path (Join-Path $root "app\\products\\loading.tsx") -Content $content_3

  $content_4Base64 = @'
aW1wb3J0IFByb2R1Y3RQYWdlU2tlbGV0b24gZnJvbSAiQC9jb21wb25lbnRzL2NvbW1vbi9Qcm9kdWN0UGFnZVNrZWxldG9uIjsKCmV4cG9ydCBkZWZhdWx0IGZ1bmN0aW9uIExvY2FsaXplZFByb2R1Y3RzTG9hZGluZygpIHsKICByZXR1cm4gPFByb2R1Y3RQYWdlU2tlbGV0b24gdmFyaWFudD0ic2VsZWN0aW9uIiAvPjsKfQo=
'@
  $content_4 = Decode-Base64Utf8 -Encoded ($content_4Base64.Trim())
  Write-Utf8NoBom -Path (Join-Path $root "app\\[locale]\\products\\loading.tsx") -Content $content_4

  $content_5Base64 = @'
aW1wb3J0IFByb2R1Y3RQYWdlU2tlbGV0b24gZnJvbSAiQC9jb21wb25lbnRzL2NvbW1vbi9Qcm9kdWN0UGFnZVNrZWxldG9uIjsKCmV4cG9ydCBkZWZhdWx0IGZ1bmN0aW9uIFByb2R1Y3REZXRhaWxMb2FkaW5nKCkgewogIHJldHVybiA8UHJvZHVjdFBhZ2VTa2VsZXRvbiB2YXJpYW50PSJkZXRhaWwiIC8+Owp9Cg==
'@
  $content_5 = Decode-Base64Utf8 -Encoded ($content_5Base64.Trim())
  Write-Utf8NoBom -Path (Join-Path $root "app\\products\\[category]\\[slug]\\loading.tsx") -Content $content_5

  Ensure-SkeletonFallback -Path $zhPagePath -LocaleExpression "zh"
  Ensure-SkeletonFallback -Path $localePagePath -LocaleExpression "productSelectionLocale"

  $nextPath = Join-Path $root ".next"

  if (Test-Path -LiteralPath $nextPath) {
    Remove-Item -LiteralPath $nextPath -Recurse -Force
    Write-Host "已清理 .next 缓存。" -ForegroundColor Yellow
  }

  Write-Host ""
  Write-Host "正在运行 npm run build……" -ForegroundColor Cyan

  & npm run build

  if ($LASTEXITCODE -ne 0) {
    throw "构建失败。"
  }

  Write-Host ""
  Write-Host "执行完成：" -ForegroundColor Green
  Write-Host " - 产品中心页面切换时先显示骨架"
  Write-Host " - 产品详情页切换时先显示骨架"
  Write-Host " - Footer 不会在正文加载前提前顶上来"
  Write-Host " - 中文与多语言产品中心 Suspense 已使用骨架 fallback"
  Write-Host " - npm run build 已通过"
}
catch {
  Write-Host ""
  Write-Host "执行失败：$($_.Exception.Message)" -ForegroundColor Red
  Write-Host "正在恢复本次修改……" -ForegroundColor Yellow

  foreach ($path in $backupMap.Keys) {
    $backupPath = $backupMap[$path]

    if (Test-Path -LiteralPath $backupPath) {
      Copy-Item -LiteralPath $backupPath -Destination $path -Force
    }
  }

  foreach ($createdFile in $createdFiles) {
    if (Test-Path -LiteralPath $createdFile) {
      Remove-Item -LiteralPath $createdFile -Force
    }
  }

  Write-Host "本次修改已恢复。" -ForegroundColor Yellow
  throw
}
