$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$root = (Get-Location).Path
$packagePath = Join-Path $root "package.json"
$cnApplicationsPath = Join-Path $root "app\applications"
$intlApplicationsPath = Join-Path $root "app\[locale]\applications"

foreach ($requiredPath in @(
  $packagePath,
  $cnApplicationsPath,
  $intlApplicationsPath
)) {
  if (-not (Test-Path -LiteralPath $requiredPath)) {
    throw "没有找到必要路径：$requiredPath"
  }
}

$stamp = Get-Date -Format "yyyyMMdd-HHmmss"
$backupMap = @{}
$createdFiles = New-Object System.Collections.Generic.List[string]

function Backup-File {
  param([string]$Path)

  if (-not (Test-Path -LiteralPath $Path)) {
    return
  }

  if ($script:backupMap.ContainsKey($Path)) {
    return
  }

  $backupPath = $Path + "." + $stamp + ".bak"
  Copy-Item -LiteralPath $Path -Destination $backupPath -Force
  $script:backupMap[$Path] = $backupPath

  Write-Host "已备份：$backupPath" -ForegroundColor Yellow
}

function Write-Utf8NoBom {
  param(
    [string]$Path,
    [string]$Content
  )

  $directory = Split-Path -Parent $Path

  if (-not (Test-Path -LiteralPath $directory)) {
    New-Item -ItemType Directory -Path $directory -Force | Out-Null
  }

  if (Test-Path -LiteralPath $Path) {
    Backup-File -Path $Path
  }
  else {
    $script:createdFiles.Add($Path)
  }

  $encoding = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($Path, $Content, $encoding)
}

function Decode-Base64Utf8 {
  param([string]$Encoded)

  $bytes = [System.Convert]::FromBase64String($Encoded)
  return [System.Text.Encoding]::UTF8.GetString($bytes)
}

function Update-ApplicationPageFallback {
  param([string]$Path)

  $content = Get-Content -LiteralPath $Path -Raw -Encoding UTF8

  if ($content -notmatch 'fallback=\{\s*null\s*\}') {
    return
  }

  Backup-File -Path $Path

  if ($content -notmatch 'import\s+ApplicationPageSkeleton\s+from\s+["'']@/components/common/ApplicationPageSkeleton["'']') {
    $firstImportIndex = $content.IndexOf("import ")

    if ($firstImportIndex -lt 0) {
      throw "无法在页面中找到 import 插入位置：$Path"
    }

    $skeletonImport = 'import ApplicationPageSkeleton from "@/components/common/ApplicationPageSkeleton";'
    $content = $content.Insert(
      $firstImportIndex,
      $skeletonImport + [Environment]::NewLine
    )
  }

  $content = [Regex]::Replace(
    $content,
    'fallback=\{\s*null\s*\}',
    'fallback={<ApplicationPageSkeleton />}'
  )

  $encoding = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($Path, $content, $encoding)

  Write-Host "已更新骨架 fallback：$Path" -ForegroundColor Green
}

try {

  $contentBase641 = @'
InVzZSBjbGllbnQiOwoKLyogPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09CiAgIEFwcGxpY2F0aW9uUGFnZVNrZWxldG9uLnRzeAogICDmgZLmsLjovr7lrpjnvZHvvZzlupTnlKjpoobln5/pobXpnaLliqDovb3pqqjmnrYKCiAgIOivtOaYju+8mgogICAxLiDnlKjkuo4gSVZE44CB5a6e6aqM5a6k6Ieq5Yqo5YyW44CB55Sf5ZG956eR5a2m44CB5YiG5p6Q5Luq5Zmo44CBCiAgICAgIOeOr+S/neebkea1i+OAgeWQiOaIkOeUn+eJqeetieW6lOeUqOmihuWfn+mhtemdogogICAyLiDpobXpnaLliIfmjaLml7blhYjmmL7npLrnu5PmnoTmoYbmnrYKICAgMy4g6Ziy5q2i5q2j5paH5pqC5pe25Li656m65pe2IEZvb3RlciDmj5DliY3pobbkuIrmnaUKPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09ICovCgppbXBvcnQgc3R5bGVzIGZyb20gIi4vQXBwbGljYXRpb25QYWdlU2tlbGV0b24ubW9kdWxlLmNzcyI7CgpmdW5jdGlvbiBTa2VsZXRvbkJsb2NrKHsKICBjbGFzc05hbWUgPSAiIiwKfTogewogIGNsYXNzTmFtZT86IHN0cmluZzsKfSkgewogIHJldHVybiAoCiAgICA8ZGl2CiAgICAgIGNsYXNzTmFtZT17W3N0eWxlcy5ibG9jaywgY2xhc3NOYW1lXQogICAgICAgIC5maWx0ZXIoQm9vbGVhbikKICAgICAgICAuam9pbigiICIpfQogICAgLz4KICApOwp9CgpleHBvcnQgZGVmYXVsdCBmdW5jdGlvbiBBcHBsaWNhdGlvblBhZ2VTa2VsZXRvbigpIHsKICByZXR1cm4gKAogICAgPHNlY3Rpb24KICAgICAgY2xhc3NOYW1lPXtzdHlsZXMucGFnZX0KICAgICAgYXJpYS1sYWJlbD0i5bqU55So6aKG5Z+f6aG16Z2i5Yqg6L295LitIgogICAgICBhcmlhLWJ1c3k9InRydWUiCiAgICA+CiAgICAgIDxkaXYgY2xhc3NOYW1lPXtzdHlsZXMuYmFubmVyfT4KICAgICAgICA8ZGl2IGNsYXNzTmFtZT17c3R5bGVzLmJhbm5lck92ZXJsYXl9PgogICAgICAgICAgPGRpdiBjbGFzc05hbWU9e3N0eWxlcy5jb250YWluZXJ9PgogICAgICAgICAgICA8U2tlbGV0b25CbG9jayBjbGFzc05hbWU9e3N0eWxlcy5iYW5uZXJUaXRsZX0gLz4KICAgICAgICAgICAgPFNrZWxldG9uQmxvY2sgY2xhc3NOYW1lPXtzdHlsZXMuYmFubmVyU3VidGl0bGV9IC8+CiAgICAgICAgICA8L2Rpdj4KICAgICAgICA8L2Rpdj4KICAgICAgPC9kaXY+CgogICAgICA8ZGl2IGNsYXNzTmFtZT17c3R5bGVzLm5hdkJhbmR9PgogICAgICAgIDxkaXYgY2xhc3NOYW1lPXtzdHlsZXMuY29udGFpbmVyfT4KICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPXtzdHlsZXMubmF2SXRlbXN9PgogICAgICAgICAgICB7QXJyYXkuZnJvbSh7IGxlbmd0aDogNiB9KS5tYXAoKF8sIGluZGV4KSA9PiAoCiAgICAgICAgICAgICAgPFNrZWxldG9uQmxvY2sKICAgICAgICAgICAgICAgIGtleT17aW5kZXh9CiAgICAgICAgICAgICAgICBjbGFzc05hbWU9e3N0eWxlcy5uYXZJdGVtfQogICAgICAgICAgICAgIC8+CiAgICAgICAgICAgICkpfQogICAgICAgICAgPC9kaXY+CiAgICAgICAgPC9kaXY+CiAgICAgIDwvZGl2PgoKICAgICAgPGRpdiBjbGFzc05hbWU9e3N0eWxlcy5jb250YWluZXJ9PgogICAgICAgIDxzZWN0aW9uIGNsYXNzTmFtZT17c3R5bGVzLmludHJvU2VjdGlvbn0+CiAgICAgICAgICA8U2tlbGV0b25CbG9jayBjbGFzc05hbWU9e3N0eWxlcy5zZWN0aW9uRXllYnJvd30gLz4KICAgICAgICAgIDxTa2VsZXRvbkJsb2NrIGNsYXNzTmFtZT17c3R5bGVzLnNlY3Rpb25UaXRsZX0gLz4KCiAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT17c3R5bGVzLmludHJvTGluZXN9PgogICAgICAgICAgICA8U2tlbGV0b25CbG9jayBjbGFzc05hbWU9e3N0eWxlcy5pbnRyb0xpbmV9IC8+CiAgICAgICAgICAgIDxTa2VsZXRvbkJsb2NrIGNsYXNzTmFtZT17c3R5bGVzLmludHJvTGluZX0gLz4KICAgICAgICAgICAgPFNrZWxldG9uQmxvY2sgY2xhc3NOYW1lPXtzdHlsZXMuaW50cm9MaW5lU2hvcnR9IC8+CiAgICAgICAgICA8L2Rpdj4KICAgICAgICA8L3NlY3Rpb24+CgogICAgICAgIDxzZWN0aW9uIGNsYXNzTmFtZT17c3R5bGVzLmZlYXR1cmVHcmlkfT4KICAgICAgICAgIHtBcnJheS5mcm9tKHsgbGVuZ3RoOiAzIH0pLm1hcCgoXywgaW5kZXgpID0+ICgKICAgICAgICAgICAgPGFydGljbGUKICAgICAgICAgICAgICBrZXk9e2luZGV4fQogICAgICAgICAgICAgIGNsYXNzTmFtZT17c3R5bGVzLmZlYXR1cmVDYXJkfQogICAgICAgICAgICA+CiAgICAgICAgICAgICAgPFNrZWxldG9uQmxvY2sgY2xhc3NOYW1lPXtzdHlsZXMuZmVhdHVyZUltYWdlfSAvPgogICAgICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPXtzdHlsZXMuZmVhdHVyZUNvbnRlbnR9PgogICAgICAgICAgICAgICAgPFNrZWxldG9uQmxvY2sgY2xhc3NOYW1lPXtzdHlsZXMuZmVhdHVyZU51bWJlcn0gLz4KICAgICAgICAgICAgICAgIDxTa2VsZXRvbkJsb2NrIGNsYXNzTmFtZT17c3R5bGVzLmZlYXR1cmVUaXRsZX0gLz4KICAgICAgICAgICAgICAgIDxTa2VsZXRvbkJsb2NrIGNsYXNzTmFtZT17c3R5bGVzLmZlYXR1cmVUZXh0fSAvPgogICAgICAgICAgICAgICAgPFNrZWxldG9uQmxvY2sgY2xhc3NOYW1lPXtzdHlsZXMuZmVhdHVyZVRleHRTaG9ydH0gLz4KICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgPC9hcnRpY2xlPgogICAgICAgICAgKSl9CiAgICAgICAgPC9zZWN0aW9uPgoKICAgICAgICA8c2VjdGlvbiBjbGFzc05hbWU9e3N0eWxlcy5zY2VuZVNlY3Rpb259PgogICAgICAgICAgPFNrZWxldG9uQmxvY2sgY2xhc3NOYW1lPXtzdHlsZXMuc2VjdGlvbkV5ZWJyb3d9IC8+CiAgICAgICAgICA8U2tlbGV0b25CbG9jayBjbGFzc05hbWU9e3N0eWxlcy5zZWN0aW9uVGl0bGVXaWRlfSAvPgoKICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPXtzdHlsZXMuc2NlbmVHcmlkfT4KICAgICAgICAgICAge0FycmF5LmZyb20oeyBsZW5ndGg6IDYgfSkubWFwKChfLCBpbmRleCkgPT4gKAogICAgICAgICAgICAgIDxhcnRpY2xlCiAgICAgICAgICAgICAgICBrZXk9e2luZGV4fQogICAgICAgICAgICAgICAgY2xhc3NOYW1lPXtzdHlsZXMuc2NlbmVDYXJkfQogICAgICAgICAgICAgID4KICAgICAgICAgICAgICAgIDxTa2VsZXRvbkJsb2NrIGNsYXNzTmFtZT17c3R5bGVzLnNjZW5lSW1hZ2V9IC8+CiAgICAgICAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT17c3R5bGVzLnNjZW5lQ29udGVudH0+CiAgICAgICAgICAgICAgICAgIDxTa2VsZXRvbkJsb2NrIGNsYXNzTmFtZT17c3R5bGVzLnNjZW5lSW5kZXh9IC8+CiAgICAgICAgICAgICAgICAgIDxTa2VsZXRvbkJsb2NrIGNsYXNzTmFtZT17c3R5bGVzLnNjZW5lVGl0bGV9IC8+CiAgICAgICAgICAgICAgICAgIDxTa2VsZXRvbkJsb2NrIGNsYXNzTmFtZT17c3R5bGVzLnNjZW5lVGV4dH0gLz4KICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICAgIDwvYXJ0aWNsZT4KICAgICAgICAgICAgKSl9CiAgICAgICAgICA8L2Rpdj4KICAgICAgICA8L3NlY3Rpb24+CiAgICAgIDwvZGl2PgogICAgPC9zZWN0aW9uPgogICk7Cn0K
'@

  $content1 = Decode-Base64Utf8 -Encoded ($contentBase641.Trim())
  Write-Utf8NoBom -Path (Join-Path $root "components\common\ApplicationPageSkeleton.tsx") -Content $content1

  $contentBase642 = @'
LyogPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09CiAgIEFwcGxpY2F0aW9uUGFnZVNrZWxldG9uLm1vZHVsZS5jc3MKICAg5oGS5rC46L6+5a6Y572R772c5bqU55So6aKG5Z+f6aG16Z2i5Yqg6L296aqo5p62Cj09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PSAqLwoKLnBhZ2UgewogIHdpZHRoOiAxMDAlOwogIG1pbi13aWR0aDogMDsKICBtaW4taGVpZ2h0OiAxMjAwcHg7CiAgYmFja2dyb3VuZDogI2ZmZmZmZjsKfQoKLmNvbnRhaW5lciB7CiAgd2lkdGg6IG1pbigxNjAwcHgsIGNhbGMoMTAwJSAtIDQ4cHgpKTsKICBtYXJnaW46IDAgYXV0bzsKfQoKLmJsb2NrIHsKICBwb3NpdGlvbjogcmVsYXRpdmU7CiAgb3ZlcmZsb3c6IGhpZGRlbjsKICBiYWNrZ3JvdW5kOiAjZTllZWY0Owp9CgouYmxvY2s6OmFmdGVyIHsKICBjb250ZW50OiAiIjsKICBwb3NpdGlvbjogYWJzb2x1dGU7CiAgaW5zZXQ6IDA7CiAgdHJhbnNmb3JtOiB0cmFuc2xhdGVYKC0xMDAlKTsKICBiYWNrZ3JvdW5kOiBsaW5lYXItZ3JhZGllbnQoCiAgICA5MGRlZywKICAgIHRyYW5zcGFyZW50IDAlLAogICAgcmdiYSgyNTUsIDI1NSwgMjU1LCAwLjc1KSA1MCUsCiAgICB0cmFuc3BhcmVudCAxMDAlCiAgKTsKICBhbmltYXRpb246IGFwcGxpY2F0aW9uU2tlbGV0b25TaGltbWVyIDEuNHMgZWFzZS1pbi1vdXQgaW5maW5pdGU7Cn0KCkBrZXlmcmFtZXMgYXBwbGljYXRpb25Ta2VsZXRvblNoaW1tZXIgewogIDEwMCUgewogICAgdHJhbnNmb3JtOiB0cmFuc2xhdGVYKDEwMCUpOwogIH0KfQoKLmJhbm5lciB7CiAgcG9zaXRpb246IHJlbGF0aXZlOwogIGhlaWdodDogNDUwcHg7CiAgcGFkZGluZy10b3A6IDgycHg7CiAgYmFja2dyb3VuZDogI2RmZTdlZjsKfQoKLmJhbm5lck92ZXJsYXkgewogIGRpc3BsYXk6IGZsZXg7CiAgaGVpZ2h0OiAxMDAlOwogIGFsaWduLWl0ZW1zOiBjZW50ZXI7CiAgYmFja2dyb3VuZDogbGluZWFyLWdyYWRpZW50KAogICAgOTBkZWcsCiAgICByZ2JhKDIzLCA1MSwgMTA0LCAwLjIpLAogICAgcmdiYSgyMywgNTEsIDEwNCwgMC4wNCkKICApOwp9CgouYmFubmVyVGl0bGUgewogIHdpZHRoOiBtaW4oNTIwcHgsIDcyJSk7CiAgaGVpZ2h0OiA0NHB4OwogIG1hcmdpbi1ib3R0b206IDIwcHg7CiAgYmFja2dyb3VuZDogcmdiYSgyNTUsIDI1NSwgMjU1LCAwLjcyKTsKfQoKLmJhbm5lclN1YnRpdGxlIHsKICB3aWR0aDogbWluKDY4MHB4LCA4OCUpOwogIGhlaWdodDogMjBweDsKICBiYWNrZ3JvdW5kOiByZ2JhKDI1NSwgMjU1LCAyNTUsIDAuNTYpOwp9CgoubmF2QmFuZCB7CiAgYm9yZGVyLWJvdHRvbTogMXB4IHNvbGlkIHJnYmEoMjMsIDUxLCAxMDQsIDAuMTIpOwogIGJhY2tncm91bmQ6ICNmZmZmZmY7Cn0KCi5uYXZJdGVtcyB7CiAgZGlzcGxheTogZ3JpZDsKICBncmlkLXRlbXBsYXRlLWNvbHVtbnM6IHJlcGVhdCg2LCBtaW5tYXgoMCwgMWZyKSk7CiAgZ2FwOiAxMnB4OwogIHBhZGRpbmc6IDIwcHggMDsKfQoKLm5hdkl0ZW0gewogIGhlaWdodDogNDJweDsKfQoKLmludHJvU2VjdGlvbiB7CiAgcGFkZGluZzogNzRweCAwIDQ0cHg7CiAgdGV4dC1hbGlnbjogY2VudGVyOwp9Cgouc2VjdGlvbkV5ZWJyb3cgewogIHdpZHRoOiAxMTBweDsKICBoZWlnaHQ6IDE0cHg7CiAgbWFyZ2luOiAwIGF1dG8gMTZweDsKfQoKLnNlY3Rpb25UaXRsZSB7CiAgd2lkdGg6IG1pbig0ODBweCwgNjglKTsKICBoZWlnaHQ6IDM0cHg7CiAgbWFyZ2luOiAwIGF1dG8gMjZweDsKfQoKLnNlY3Rpb25UaXRsZVdpZGUgewogIHdpZHRoOiBtaW4oNjIwcHgsIDc4JSk7CiAgaGVpZ2h0OiAzNHB4OwogIG1hcmdpbjogMCBhdXRvIDMwcHg7Cn0KCi5pbnRyb0xpbmVzIHsKICBkaXNwbGF5OiBncmlkOwogIGp1c3RpZnktaXRlbXM6IGNlbnRlcjsKICBnYXA6IDExcHg7Cn0KCi5pbnRyb0xpbmUgewogIHdpZHRoOiBtaW4oOTAwcHgsIDgyJSk7CiAgaGVpZ2h0OiAxNXB4Owp9CgouaW50cm9MaW5lU2hvcnQgewogIHdpZHRoOiBtaW4oNjIwcHgsIDYyJSk7CiAgaGVpZ2h0OiAxNXB4Owp9CgouZmVhdHVyZUdyaWQgewogIGRpc3BsYXk6IGdyaWQ7CiAgZ3JpZC10ZW1wbGF0ZS1jb2x1bW5zOiByZXBlYXQoMywgbWlubWF4KDAsIDFmcikpOwogIGdhcDogMjRweDsKICBwYWRkaW5nLWJvdHRvbTogODZweDsKfQoKLmZlYXR1cmVDYXJkIHsKICBtaW4td2lkdGg6IDA7CiAgYm9yZGVyOiAxcHggc29saWQgcmdiYSgyMywgNTEsIDEwNCwgMC4xMik7CiAgYmFja2dyb3VuZDogI2ZmZmZmZjsKfQoKLmZlYXR1cmVJbWFnZSB7CiAgd2lkdGg6IDEwMCU7CiAgYXNwZWN0LXJhdGlvOiAxNiAvIDEwOwp9CgouZmVhdHVyZUNvbnRlbnQgewogIHBhZGRpbmc6IDI0cHg7Cn0KCi5mZWF0dXJlTnVtYmVyIHsKICB3aWR0aDogNDRweDsKICBoZWlnaHQ6IDE0cHg7CiAgbWFyZ2luLWJvdHRvbTogMThweDsKfQoKLmZlYXR1cmVUaXRsZSB7CiAgd2lkdGg6IDY0JTsKICBoZWlnaHQ6IDIzcHg7CiAgbWFyZ2luLWJvdHRvbTogMThweDsKfQoKLmZlYXR1cmVUZXh0IHsKICB3aWR0aDogMTAwJTsKICBoZWlnaHQ6IDE0cHg7CiAgbWFyZ2luLWJvdHRvbTogMTBweDsKfQoKLmZlYXR1cmVUZXh0U2hvcnQgewogIHdpZHRoOiA3NCU7CiAgaGVpZ2h0OiAxNHB4Owp9Cgouc2NlbmVTZWN0aW9uIHsKICBwYWRkaW5nOiA4MHB4IDAgMTAwcHg7CiAgYm9yZGVyLXRvcDogMXB4IHNvbGlkIHJnYmEoMjMsIDUxLCAxMDQsIDAuMSk7Cn0KCi5zY2VuZUdyaWQgewogIGRpc3BsYXk6IGdyaWQ7CiAgZ3JpZC10ZW1wbGF0ZS1jb2x1bW5zOiByZXBlYXQoMywgbWlubWF4KDAsIDFmcikpOwogIGdhcDogMjJweDsKfQoKLnNjZW5lQ2FyZCB7CiAgbWluLXdpZHRoOiAwOwogIGJvcmRlcjogMXB4IHNvbGlkIHJnYmEoMjMsIDUxLCAxMDQsIDAuMTIpOwogIGJhY2tncm91bmQ6ICNmZmZmZmY7Cn0KCi5zY2VuZUltYWdlIHsKICB3aWR0aDogMTAwJTsKICBhc3BlY3QtcmF0aW86IDE2IC8gOTsKfQoKLnNjZW5lQ29udGVudCB7CiAgcGFkZGluZzogMjJweDsKfQoKLnNjZW5lSW5kZXggewogIHdpZHRoOiAzNHB4OwogIGhlaWdodDogMTNweDsKICBtYXJnaW4tYm90dG9tOiAxNHB4Owp9Cgouc2NlbmVUaXRsZSB7CiAgd2lkdGg6IDY4JTsKICBoZWlnaHQ6IDIxcHg7CiAgbWFyZ2luLWJvdHRvbTogMTRweDsKfQoKLnNjZW5lVGV4dCB7CiAgd2lkdGg6IDg4JTsKICBoZWlnaHQ6IDE0cHg7Cn0KCkBtZWRpYSAobWF4LXdpZHRoOiAxMDAwcHgpIHsKICAubmF2SXRlbXMgewogICAgZ3JpZC10ZW1wbGF0ZS1jb2x1bW5zOiByZXBlYXQoMywgbWlubWF4KDAsIDFmcikpOwogIH0KCiAgLmZlYXR1cmVHcmlkLAogIC5zY2VuZUdyaWQgewogICAgZ3JpZC10ZW1wbGF0ZS1jb2x1bW5zOiByZXBlYXQoMiwgbWlubWF4KDAsIDFmcikpOwogIH0KfQoKQG1lZGlhIChtYXgtd2lkdGg6IDc2MHB4KSB7CiAgLnBhZ2UgewogICAgbWluLWhlaWdodDogOTAwcHg7CiAgfQoKICAuY29udGFpbmVyIHsKICAgIHdpZHRoOiBjYWxjKDEwMCUgLSAyNHB4KTsKICB9CgogIC5iYW5uZXIgewogICAgaGVpZ2h0OiAzNjBweDsKICAgIHBhZGRpbmctdG9wOiA3MHB4OwogIH0KCiAgLmJhbm5lclRpdGxlIHsKICAgIHdpZHRoOiA3OCU7CiAgICBoZWlnaHQ6IDM0cHg7CiAgfQoKICAuYmFubmVyU3VidGl0bGUgewogICAgd2lkdGg6IDkyJTsKICAgIGhlaWdodDogMTdweDsKICB9CgogIC5uYXZJdGVtcyB7CiAgICBncmlkLXRlbXBsYXRlLWNvbHVtbnM6IHJlcGVhdCgzLCBtaW5tYXgoMCwgMWZyKSk7CiAgICBnYXA6IDhweDsKICAgIHBhZGRpbmc6IDE0cHggMDsKICB9CgogIC5uYXZJdGVtIHsKICAgIGhlaWdodDogMzhweDsKICB9CgogIC5pbnRyb1NlY3Rpb24gewogICAgcGFkZGluZzogNTBweCAwIDMycHg7CiAgfQoKICAuZmVhdHVyZUdyaWQsCiAgLnNjZW5lR3JpZCB7CiAgICBncmlkLXRlbXBsYXRlLWNvbHVtbnM6IDFmcjsKICB9CgogIC5mZWF0dXJlR3JpZCB7CiAgICBnYXA6IDE2cHg7CiAgICBwYWRkaW5nLWJvdHRvbTogNTZweDsKICB9CgogIC5mZWF0dXJlR3JpZCAuZmVhdHVyZUNhcmQ6bnRoLWNoaWxkKG4gKyAzKSB7CiAgICBkaXNwbGF5OiBub25lOwogIH0KCiAgLnNjZW5lU2VjdGlvbiB7CiAgICBwYWRkaW5nOiA1NnB4IDAgNjRweDsKICB9CgogIC5zY2VuZUdyaWQgewogICAgZ2FwOiAxNHB4OwogIH0KCiAgLnNjZW5lR3JpZCAuc2NlbmVDYXJkOm50aC1jaGlsZChuICsgNCkgewogICAgZGlzcGxheTogbm9uZTsKICB9CgogIC5mZWF0dXJlQ29udGVudCwKICAuc2NlbmVDb250ZW50IHsKICAgIHBhZGRpbmc6IDE4cHg7CiAgfQp9CgpAbWVkaWEgKHByZWZlcnMtcmVkdWNlZC1tb3Rpb246IHJlZHVjZSkgewogIC5ibG9jazo6YWZ0ZXIgewogICAgYW5pbWF0aW9uOiBub25lOwogIH0KfQo=
'@

  $content2 = Decode-Base64Utf8 -Encoded ($contentBase642.Trim())
  Write-Utf8NoBom -Path (Join-Path $root "components\common\ApplicationPageSkeleton.module.css") -Content $content2

  $contentBase643 = @'
aW1wb3J0IEFwcGxpY2F0aW9uUGFnZVNrZWxldG9uIGZyb20gIkAvY29tcG9uZW50cy9jb21tb24vQXBwbGljYXRpb25QYWdlU2tlbGV0b24iOwoKZXhwb3J0IGRlZmF1bHQgZnVuY3Rpb24gQXBwbGljYXRpb25zTG9hZGluZygpIHsKICByZXR1cm4gPEFwcGxpY2F0aW9uUGFnZVNrZWxldG9uIC8+Owp9Cg==
'@

  $content3 = Decode-Base64Utf8 -Encoded ($contentBase643.Trim())
  Write-Utf8NoBom -Path (Join-Path $root "app\applications\loading.tsx") -Content $content3

  $contentBase644 = @'
aW1wb3J0IEFwcGxpY2F0aW9uUGFnZVNrZWxldG9uIGZyb20gIkAvY29tcG9uZW50cy9jb21tb24vQXBwbGljYXRpb25QYWdlU2tlbGV0b24iOwoKZXhwb3J0IGRlZmF1bHQgZnVuY3Rpb24gTG9jYWxpemVkQXBwbGljYXRpb25zTG9hZGluZygpIHsKICByZXR1cm4gPEFwcGxpY2F0aW9uUGFnZVNrZWxldG9uIC8+Owp9Cg==
'@

  $content4 = Decode-Base64Utf8 -Encoded ($contentBase644.Trim())
  Write-Utf8NoBom -Path (Join-Path $root "app\[locale]\applications\loading.tsx") -Content $content4

  $applicationPages = New-Object System.Collections.Generic.List[string]

  Get-ChildItem -LiteralPath $cnApplicationsPath -Recurse -File -Filter "page.tsx" |
    ForEach-Object {
      $applicationPages.Add($_.FullName)
    }

  Get-ChildItem -LiteralPath $intlApplicationsPath -Recurse -File -Filter "page.tsx" |
    ForEach-Object {
      $applicationPages.Add($_.FullName)
    }

  foreach ($pagePath in $applicationPages) {
    Update-ApplicationPageFallback -Path $pagePath
  }

  $nextPath = Join-Path $root ".next"

  if (Test-Path -LiteralPath $nextPath) {
    Remove-Item -LiteralPath $nextPath -Recurse -Force
    Write-Host "已清理 .next 缓存。" -ForegroundColor Yellow
  }

  Write-Host ""
  Write-Host "正在运行 npm run build……" -ForegroundColor Cyan

  & npm run build

  if ($LASTEXITCODE -ne 0) {
    throw "构建失败。"
  }

  Write-Host ""
  Write-Host "执行完成：" -ForegroundColor Green
  Write-Host " - 中文应用领域页面已加入统一骨架"
  Write-Host " - 多语言应用领域页面已加入统一骨架"
  Write-Host " - 所有 fallback={null} 已替换为应用页面骨架"
  Write-Host " - Banner、导航、介绍、卡片区域会先占位"
  Write-Host " - Footer 不会在正文加载前提前顶上来"
  Write-Host " - npm run build 已通过"
}
catch {
  Write-Host ""
  Write-Host "执行失败：$($_.Exception.Message)" -ForegroundColor Red
  Write-Host "正在恢复本次修改……" -ForegroundColor Yellow

  foreach ($path in $backupMap.Keys) {
    $backupPath = $backupMap[$path]

    if (Test-Path -LiteralPath $backupPath) {
      Copy-Item -LiteralPath $backupPath -Destination $path -Force
    }
  }

  foreach ($createdFile in $createdFiles) {
    if (Test-Path -LiteralPath $createdFile) {
      Remove-Item -LiteralPath $createdFile -Force
    }
  }

  Write-Host "本次修改已恢复。" -ForegroundColor Yellow
  throw
}
