import type { LocaleCode } from "@/lib/i18n";

type InternationalLocale = Exclude<LocaleCode, "zh-CN" | "en">;

const translations: Record<InternationalLocale, Record<string, string>> = {
  es: {
    "Site Search": "Búsqueda del sitio", "Site search results": "Resultados de búsqueda", Search: "Buscar", Searching: "Buscando…", "Search products and technical resources": "Buscar productos y recursos técnicos", "Search by product name, model, compatible model, datasheet, guide, or technical keyword.": "Busque por nombre de producto, modelo, modelo compatible, ficha técnica, guía o palabra clave técnica.", "Enter another character": "Introduzca otro carácter", "Enter at least two letters or numbers.": "Introduzca al menos dos letras o números.", "Search data could not be loaded": "No se pudieron cargar los datos de búsqueda", "Refresh the page and try again.": "Actualice la página e inténtelo de nuevo.", "No matching results": "No se encontraron resultados", "Check the model number or try a product name, series, material, or application keyword.": "Compruebe el modelo o pruebe con un producto, serie, material o aplicación.", "Show Less": "Mostrar menos", "Show More": "Mostrar más", results: "resultados", remaining: "restantes",
    Products: "Productos", "View Product": "Ver producto", "Compatible Model Search": "Búsqueda de modelos compatibles", "View Compatible Product": "Ver producto compatible", Datasheets: "Fichas técnicas", "View Datasheet": "Ver ficha técnica", "Installation Guides": "Guías de instalación", "View Guide": "Ver guía", "Technical Articles": "Artículos técnicos", "Read Article": "Leer artículo", "Material Compatibility": "Compatibilidad de materiales", "View Material Data": "Ver datos del material", Applications: "Aplicaciones", "View Application": "Ver aplicación", News: "Noticias", "View News": "Ver noticia", Pages: "Páginas", "Open Page": "Abrir página",
    "Product Selection List": "Lista de selección de productos", "No products selected": "No hay productos seleccionados", ProductsCount: "Productos", "Drawing Requests": "Solicitudes de planos", Top: "Arriba", List: "Lista", Close: "Cerrar", Quantity: "Cantidad", "Product Type": "Tipo de producto", "Product Model": "Modelo de producto", "Product Code": "Código de producto", "Compatible Models": "Modelos compatibles", "Add Drawing": "Añadir plano", "Drawing Added": "Plano añadido", "Request Drawings": "Solicitar planos", "Generate PDF List": "Generar lista PDF", "Copy List": "Copiar lista", Clear: "Vaciar", Remove: "Eliminar",
    "Search products, models, compatible models, and datasheets across the FOREACH website.": "Busque productos, modelos, equivalencias y fichas técnicas en el sitio web de FOREACH.", "Search products, models, compatible models, or datasheets": "Buscar productos, modelos, equivalencias o fichas técnicas", "Enter a search term": "Introduzca un término de búsqueda", "For example: Q2002, PMC1702, plunger pump, or diaphragm pump datasheet.": "Por ejemplo: Q2002, PMC1702, bomba de émbolo o ficha técnica de bomba de diafragma.", "Search Term": "Término de búsqueda", "Check the model number or try a product name, series, or another keyword.": "Compruebe el modelo o pruebe con un producto, una serie u otra palabra clave.", "View Details": "Ver detalles",
    "View product details and selection information.": "Consulte los detalles del producto y la información de selección.", "View the corresponding FOREACH compatible product.": "Consulte el producto FOREACH compatible correspondiente.", "View or download the available product datasheet.": "Consulte o descargue la ficha técnica disponible del producto.", "View installation and commissioning guidance.": "Consulte las instrucciones de instalación y puesta en marcha.", "Read the full technical article.": "Lea el artículo técnico completo.", "Review material compatibility information.": "Consulte la información sobre compatibilidad de materiales.", "Explore the related fluid handling application.": "Explore la aplicación relacionada con el manejo de fluidos.", "Read the full FOREACH news update.": "Lea la noticia completa de FOREACH.", "Open this FOREACH website page.": "Abra esta página del sitio web de FOREACH.",
  },
  fr: {
    "Site Search": "Recherche sur le site", "Site search results": "Résultats de recherche", Search: "Rechercher", Searching: "Recherche…", "Search products and technical resources": "Rechercher des produits et ressources techniques", "Search by product name, model, compatible model, datasheet, guide, or technical keyword.": "Recherchez par produit, modèle, modèle compatible, fiche technique, guide ou mot-clé technique.", "Enter another character": "Saisissez un autre caractère", "Enter at least two letters or numbers.": "Saisissez au moins deux lettres ou chiffres.", "Search data could not be loaded": "Impossible de charger les données de recherche", "Refresh the page and try again.": "Actualisez la page et réessayez.", "No matching results": "Aucun résultat correspondant", "Check the model number or try a product name, series, material, or application keyword.": "Vérifiez le modèle ou essayez un produit, une série, un matériau ou une application.", "Show Less": "Afficher moins", "Show More": "Afficher plus", results: "résultats", remaining: "restants",
    Products: "Produits", "View Product": "Voir le produit", "Compatible Model Search": "Recherche de modèles compatibles", "View Compatible Product": "Voir le produit compatible", Datasheets: "Fiches techniques", "View Datasheet": "Voir la fiche technique", "Installation Guides": "Guides d’installation", "View Guide": "Voir le guide", "Technical Articles": "Articles techniques", "Read Article": "Lire l’article", "Material Compatibility": "Compatibilité des matériaux", "View Material Data": "Voir les données matériau", Applications: "Applications", "View Application": "Voir l’application", News: "Actualités", "View News": "Voir l’actualité", Pages: "Pages", "Open Page": "Ouvrir la page",
    "Product Selection List": "Liste de sélection de produits", "No products selected": "Aucun produit sélectionné", ProductsCount: "Produits", "Drawing Requests": "Demandes de plans", Top: "Haut", List: "Liste", Close: "Fermer", Quantity: "Quantité", "Product Type": "Type de produit", "Product Model": "Modèle de produit", "Product Code": "Code produit", "Compatible Models": "Modèles compatibles", "Add Drawing": "Ajouter un plan", "Drawing Added": "Plan ajouté", "Request Drawings": "Demander des plans", "Generate PDF List": "Générer la liste PDF", "Copy List": "Copier la liste", Clear: "Vider", Remove: "Supprimer",
    "Search products, models, compatible models, and datasheets across the FOREACH website.": "Recherchez des produits, modèles, équivalences et fiches techniques sur le site FOREACH.", "Search products, models, compatible models, or datasheets": "Rechercher des produits, modèles, équivalences ou fiches techniques", "Enter a search term": "Saisissez un terme de recherche", "For example: Q2002, PMC1702, plunger pump, or diaphragm pump datasheet.": "Par exemple : Q2002, PMC1702, pompe à piston ou fiche technique de pompe à membrane.", "Search Term": "Terme recherché", "Check the model number or try a product name, series, or another keyword.": "Vérifiez le modèle ou essayez un produit, une série ou un autre mot-clé.", "View Details": "Voir les détails",
    "View product details and selection information.": "Consultez les détails du produit et les informations de sélection.", "View the corresponding FOREACH compatible product.": "Consultez le produit FOREACH compatible correspondant.", "View or download the available product datasheet.": "Consultez ou téléchargez la fiche technique disponible du produit.", "View installation and commissioning guidance.": "Consultez les instructions d’installation et de mise en service.", "Read the full technical article.": "Lisez l’article technique complet.", "Review material compatibility information.": "Consultez les informations sur la compatibilité des matériaux.", "Explore the related fluid handling application.": "Découvrez l’application de gestion des fluides associée.", "Read the full FOREACH news update.": "Lisez l’actualité FOREACH complète.", "Open this FOREACH website page.": "Ouvrez cette page du site FOREACH.",
  },
  ko: {
    "Site Search": "사이트 검색", "Site search results": "검색 결과", Search: "검색", Searching: "검색 중…", "Search products and technical resources": "제품 및 기술 자료 검색", "Search by product name, model, compatible model, datasheet, guide, or technical keyword.": "제품명, 모델, 호환 모델, 데이터시트, 가이드 또는 기술 키워드로 검색하세요.", "Enter another character": "문자를 더 입력하세요", "Enter at least two letters or numbers.": "영문 또는 숫자를 두 자 이상 입력하세요.", "Search data could not be loaded": "검색 데이터를 불러올 수 없습니다", "Refresh the page and try again.": "페이지를 새로고침한 후 다시 시도하세요.", "No matching results": "일치하는 결과가 없습니다", "Check the model number or try a product name, series, material, or application keyword.": "모델 번호를 확인하거나 제품, 시리즈, 소재 또는 응용 분야를 검색하세요.", "Show Less": "접기", "Show More": "더 보기", results: "개 결과", remaining: "개 남음",
    Products: "제품", "View Product": "제품 보기", "Compatible Model Search": "호환 모델 검색", "View Compatible Product": "호환 제품 보기", Datasheets: "데이터시트", "View Datasheet": "데이터시트 보기", "Installation Guides": "설치 가이드", "View Guide": "가이드 보기", "Technical Articles": "기술 자료", "Read Article": "자료 읽기", "Material Compatibility": "재료 호환성", "View Material Data": "재료 정보 보기", Applications: "응용 분야", "View Application": "응용 분야 보기", News: "뉴스", "View News": "뉴스 보기", Pages: "페이지", "Open Page": "페이지 열기",
    "Product Selection List": "제품 선택 목록", "No products selected": "선택한 제품이 없습니다", ProductsCount: "제품", "Drawing Requests": "도면 요청", Top: "맨 위", List: "목록", Close: "닫기", Quantity: "수량", "Product Type": "제품 유형", "Product Model": "제품 모델", "Product Code": "제품 코드", "Compatible Models": "호환 모델", "Add Drawing": "도면 추가", "Drawing Added": "도면 추가됨", "Request Drawings": "도면 요청", "Generate PDF List": "PDF 목록 생성", "Copy List": "목록 복사", Clear: "비우기", Remove: "삭제",
    "Search products, models, compatible models, and datasheets across the FOREACH website.": "FOREACH 웹사이트에서 제품, 모델, 호환 모델 및 데이터시트를 검색하세요.", "Search products, models, compatible models, or datasheets": "제품, 모델, 호환 모델 또는 데이터시트 검색", "Enter a search term": "검색어를 입력하세요", "For example: Q2002, PMC1702, plunger pump, or diaphragm pump datasheet.": "예: Q2002, PMC1702, 플런저 펌프 또는 다이어프램 펌프 데이터시트.", "Search Term": "검색어", "Check the model number or try a product name, series, or another keyword.": "모델 번호를 확인하거나 제품명, 시리즈명 또는 다른 키워드로 검색하세요.", "View Details": "상세 보기",
    "View product details and selection information.": "제품 상세 정보와 선정 정보를 확인하세요.", "View the corresponding FOREACH compatible product.": "해당 FOREACH 호환 제품을 확인하세요.", "View or download the available product datasheet.": "제공되는 제품 데이터시트를 확인하거나 다운로드하세요.", "View installation and commissioning guidance.": "설치 및 시운전 안내를 확인하세요.", "Read the full technical article.": "전체 기술 자료를 읽어보세요.", "Review material compatibility information.": "재료 호환성 정보를 확인하세요.", "Explore the related fluid handling application.": "관련 유체 제어 응용 분야를 살펴보세요.", "Read the full FOREACH news update.": "FOREACH 뉴스 전문을 읽어보세요.", "Open this FOREACH website page.": "이 FOREACH 웹사이트 페이지를 여세요.",
  },
  ru: {
    "Site Search": "Поиск по сайту", "Site search results": "Результаты поиска", Search: "Поиск", Searching: "Поиск…", "Search products and technical resources": "Поиск продукции и технических материалов", "Search by product name, model, compatible model, datasheet, guide, or technical keyword.": "Ищите по названию, модели, совместимой модели, техническому описанию, руководству или ключевому слову.", "Enter another character": "Введите ещё один символ", "Enter at least two letters or numbers.": "Введите не менее двух букв или цифр.", "Search data could not be loaded": "Не удалось загрузить данные поиска", "Refresh the page and try again.": "Обновите страницу и повторите попытку.", "No matching results": "Совпадений не найдено", "Check the model number or try a product name, series, material, or application keyword.": "Проверьте модель или попробуйте название продукта, серии, материала или области применения.", "Show Less": "Свернуть", "Show More": "Показать ещё", results: "результатов", remaining: "осталось",
    Products: "Продукция", "View Product": "Открыть продукт", "Compatible Model Search": "Поиск совместимых моделей", "View Compatible Product": "Открыть совместимый продукт", Datasheets: "Технические описания", "View Datasheet": "Открыть описание", "Installation Guides": "Инструкции по установке", "View Guide": "Открыть инструкцию", "Technical Articles": "Технические статьи", "Read Article": "Читать статью", "Material Compatibility": "Совместимость материалов", "View Material Data": "Данные о материале", Applications: "Применения", "View Application": "Открыть применение", News: "Новости", "View News": "Открыть новость", Pages: "Страницы", "Open Page": "Открыть страницу",
    "Product Selection List": "Список выбранных продуктов", "No products selected": "Продукты не выбраны", ProductsCount: "Продукты", "Drawing Requests": "Запросы чертежей", Top: "Наверх", List: "Список", Close: "Закрыть", Quantity: "Количество", "Product Type": "Тип продукта", "Product Model": "Модель продукта", "Product Code": "Код продукта", "Compatible Models": "Совместимые модели", "Add Drawing": "Добавить чертёж", "Drawing Added": "Чертёж добавлен", "Request Drawings": "Запросить чертежи", "Generate PDF List": "Создать PDF-список", "Copy List": "Копировать список", Clear: "Очистить", Remove: "Удалить",
    "Search products, models, compatible models, and datasheets across the FOREACH website.": "Поиск продукции, моделей, совместимых аналогов и технических описаний на сайте FOREACH.", "Search products, models, compatible models, or datasheets": "Поиск продукции, моделей, аналогов или технических описаний", "Enter a search term": "Введите поисковый запрос", "For example: Q2002, PMC1702, plunger pump, or diaphragm pump datasheet.": "Например: Q2002, PMC1702, плунжерный насос или описание мембранного насоса.", "Search Term": "Поисковый запрос", "Check the model number or try a product name, series, or another keyword.": "Проверьте модель или попробуйте название продукта, серии либо другое ключевое слово.", "View Details": "Подробнее",
    "View product details and selection information.": "Просмотрите сведения о продукте и информацию по подбору.", "View the corresponding FOREACH compatible product.": "Просмотрите соответствующий совместимый продукт FOREACH.", "View or download the available product datasheet.": "Просмотрите или скачайте доступное техническое описание продукта.", "View installation and commissioning guidance.": "Просмотрите инструкции по установке и вводу в эксплуатацию.", "Read the full technical article.": "Прочитайте техническую статью полностью.", "Review material compatibility information.": "Просмотрите информацию о совместимости материалов.", "Explore the related fluid handling application.": "Подробнее о соответствующем применении для работы с жидкостями.", "Read the full FOREACH news update.": "Прочитайте полную новость FOREACH.", "Open this FOREACH website page.": "Откройте эту страницу сайта FOREACH.",
  },
};

export function getInternationalUiText(locale: LocaleCode, englishText: string) {
  if (locale === "zh-CN" || locale === "en") return englishText;
  return translations[locale][englishText] ?? englishText;
}
