/* =========================================================
   AUTO-GENERATED FILE — DO NOT EDIT MANUALLY

   Source:
   data-source/product-center/pumps/plunger-pump/ea/
   01_EA常规柱塞泵_详情页资料_zh.xlsx

   Generated by:
   generate_ea_product_detail_data_v3_excel_com_utf8bom.ps1
========================================================= */

export type EaProductMaterial = "PMMA" | "PEEK";

export type EaProductDetailZh = {
  category: "pumps";
  productFamily: "EA常规柱塞泵";
  slug: string;
  model: string;
  name: string;
  capacity: number;
  material: EaProductMaterial;
  advantages: string[];
  commonApplications: string[];
  mainImage: string;
  additionalImages: string[];
  showConfiguration: boolean;
  showDatasheetRequest: boolean;
  show2DRequest: boolean;
  show3DRequest: boolean;
  faqSeries: string;
};

export const eaProductDetailsZh = [
    {
        "category":  "pumps",
        "productFamily":  "EA常规柱塞泵",
        "slug":  "ea-100-pmma",
        "model":  "EA-100-PMMA",
        "name":  "常规柱塞泵",
        "capacity":  100,
        "material":  "PMMA",
        "advantages":  [
                           "精密定量输送",
                           "满量程准确度≤0.5%",
                           "满量程重复性≤0.5%",
                           "支持1/4-28 UNF或M6平底接口",
                           "适合自动化液路系统集成"
                       ],
        "commonApplications":  [
                                   "IVD诊断设备",
                                   "生命科学仪器",
                                   "实验室自动化",
                                   "分析仪器"
                               ],
        "mainImage":  "/images/products/pumps/plunger-pump/ea/pump-ea-100ul-pmma.webp",
        "additionalImages":  [
                                 "/images/products/pumps/plunger-pump/ea/pump-ea-duanzi.webp",
                                 "/images/products/pumps/plunger-pump/ea/pump-ea-guangou.webp"
                             ],
        "showConfiguration":  true,
        "showDatasheetRequest":  true,
        "show2DRequest":  true,
        "show3DRequest":  true,
        "faqSeries":  "EA常规柱塞泵"
    },
    {
        "category":  "pumps",
        "productFamily":  "EA常规柱塞泵",
        "slug":  "ea-100-peek",
        "model":  "EA-100-PEEK",
        "name":  "常规柱塞泵",
        "capacity":  100,
        "material":  "PEEK",
        "advantages":  [
                           "精密定量输送",
                           "满量程准确度≤0.5%",
                           "满量程重复性≤0.5%",
                           "支持1/4-28 UNF或M6平底接口",
                           "适合自动化液路系统集成"
                       ],
        "commonApplications":  [
                                   "IVD诊断设备",
                                   "生命科学仪器",
                                   "实验室自动化",
                                   "分析仪器"
                               ],
        "mainImage":  "/images/products/pumps/plunger-pump/ea/pump-ea-100ul-peek.webp",
        "additionalImages":  [
                                 "/images/products/pumps/plunger-pump/ea/pump-ea-duanzi.webp",
                                 "/images/products/pumps/plunger-pump/ea/pump-ea-guangou.webp"
                             ],
        "showConfiguration":  true,
        "showDatasheetRequest":  true,
        "show2DRequest":  true,
        "show3DRequest":  true,
        "faqSeries":  "EA常规柱塞泵"
    },
    {
        "category":  "pumps",
        "productFamily":  "EA常规柱塞泵",
        "slug":  "ea-250-pmma",
        "model":  "EA-250-PMMA",
        "name":  "常规柱塞泵",
        "capacity":  250,
        "material":  "PMMA",
        "advantages":  [
                           "精密定量输送",
                           "满量程准确度≤0.5%",
                           "满量程重复性≤0.5%",
                           "支持1/4-28 UNF或M6平底接口",
                           "适合自动化液路系统集成"
                       ],
        "commonApplications":  [
                                   "IVD诊断设备",
                                   "生命科学仪器",
                                   "实验室自动化",
                                   "分析仪器"
                               ],
        "mainImage":  "/images/products/pumps/plunger-pump/ea/pump-ea-250ul-pmma.webp",
        "additionalImages":  [
                                 "/images/products/pumps/plunger-pump/ea/pump-ea-duanzi.webp",
                                 "/images/products/pumps/plunger-pump/ea/pump-ea-guangou.webp"
                             ],
        "showConfiguration":  true,
        "showDatasheetRequest":  true,
        "show2DRequest":  true,
        "show3DRequest":  true,
        "faqSeries":  "EA常规柱塞泵"
    },
    {
        "category":  "pumps",
        "productFamily":  "EA常规柱塞泵",
        "slug":  "ea-250-peek",
        "model":  "EA-250-PEEK",
        "name":  "常规柱塞泵",
        "capacity":  250,
        "material":  "PEEK",
        "advantages":  [
                           "精密定量输送",
                           "满量程准确度≤0.5%",
                           "满量程重复性≤0.5%",
                           "支持1/4-28 UNF或M6平底接口",
                           "适合自动化液路系统集成"
                       ],
        "commonApplications":  [
                                   "IVD诊断设备",
                                   "生命科学仪器",
                                   "实验室自动化",
                                   "分析仪器"
                               ],
        "mainImage":  "/images/products/pumps/plunger-pump/ea/pump-ea-250ul-peek.webp",
        "additionalImages":  [
                                 "/images/products/pumps/plunger-pump/ea/pump-ea-duanzi.webp",
                                 "/images/products/pumps/plunger-pump/ea/pump-ea-guangou.webp"
                             ],
        "showConfiguration":  true,
        "showDatasheetRequest":  true,
        "show2DRequest":  true,
        "show3DRequest":  true,
        "faqSeries":  "EA常规柱塞泵"
    },
    {
        "category":  "pumps",
        "productFamily":  "EA常规柱塞泵",
        "slug":  "ea-500-pmma",
        "model":  "EA-500-PMMA",
        "name":  "常规柱塞泵",
        "capacity":  500,
        "material":  "PMMA",
        "advantages":  [
                           "精密定量输送",
                           "满量程准确度≤0.5%",
                           "满量程重复性≤0.5%",
                           "支持1/4-28 UNF或M6平底接口",
                           "适合自动化液路系统集成"
                       ],
        "commonApplications":  [
                                   "IVD诊断设备",
                                   "生命科学仪器",
                                   "实验室自动化",
                                   "分析仪器"
                               ],
        "mainImage":  "/images/products/pumps/plunger-pump/ea/pump-ea-500ul-pmma.webp",
        "additionalImages":  [
                                 "/images/products/pumps/plunger-pump/ea/pump-ea-duanzi.webp",
                                 "/images/products/pumps/plunger-pump/ea/pump-ea-guangou.webp"
                             ],
        "showConfiguration":  true,
        "showDatasheetRequest":  true,
        "show2DRequest":  true,
        "show3DRequest":  true,
        "faqSeries":  "EA常规柱塞泵"
    },
    {
        "category":  "pumps",
        "productFamily":  "EA常规柱塞泵",
        "slug":  "ea-500-peek",
        "model":  "EA-500-PEEK",
        "name":  "常规柱塞泵",
        "capacity":  500,
        "material":  "PEEK",
        "advantages":  [
                           "精密定量输送",
                           "满量程准确度≤0.5%",
                           "满量程重复性≤0.5%",
                           "支持1/4-28 UNF或M6平底接口",
                           "适合自动化液路系统集成"
                       ],
        "commonApplications":  [
                                   "IVD诊断设备",
                                   "生命科学仪器",
                                   "实验室自动化",
                                   "分析仪器"
                               ],
        "mainImage":  "/images/products/pumps/plunger-pump/ea/pump-ea-500ul-peek.webp",
        "additionalImages":  [
                                 "/images/products/pumps/plunger-pump/ea/pump-ea-duanzi.webp",
                                 "/images/products/pumps/plunger-pump/ea/pump-ea-guangou.webp"
                             ],
        "showConfiguration":  true,
        "showDatasheetRequest":  true,
        "show2DRequest":  true,
        "show3DRequest":  true,
        "faqSeries":  "EA常规柱塞泵"
    },
    {
        "category":  "pumps",
        "productFamily":  "EA常规柱塞泵",
        "slug":  "ea-1000-pmma",
        "model":  "EA-1000-PMMA",
        "name":  "常规柱塞泵",
        "capacity":  1000,
        "material":  "PMMA",
        "advantages":  [
                           "精密定量输送",
                           "满量程准确度≤0.5%",
                           "满量程重复性≤0.5%",
                           "支持1/4-28 UNF或M6平底接口",
                           "适合自动化液路系统集成"
                       ],
        "commonApplications":  [
                                   "IVD诊断设备",
                                   "生命科学仪器",
                                   "实验室自动化",
                                   "分析仪器"
                               ],
        "mainImage":  "/images/products/pumps/plunger-pump/ea/pump-ea-1000ul-pmma.webp",
        "additionalImages":  [
                                 "/images/products/pumps/plunger-pump/ea/pump-ea-duanzi.webp",
                                 "/images/products/pumps/plunger-pump/ea/pump-ea-guangou.webp"
                             ],
        "showConfiguration":  true,
        "showDatasheetRequest":  true,
        "show2DRequest":  true,
        "show3DRequest":  true,
        "faqSeries":  "EA常规柱塞泵"
    },
    {
        "category":  "pumps",
        "productFamily":  "EA常规柱塞泵",
        "slug":  "ea-1000-peek",
        "model":  "EA-1000-PEEK",
        "name":  "常规柱塞泵",
        "capacity":  1000,
        "material":  "PEEK",
        "advantages":  [
                           "精密定量输送",
                           "满量程准确度≤0.5%",
                           "满量程重复性≤0.5%",
                           "支持1/4-28 UNF或M6平底接口",
                           "适合自动化液路系统集成"
                       ],
        "commonApplications":  [
                                   "IVD诊断设备",
                                   "生命科学仪器",
                                   "实验室自动化",
                                   "分析仪器"
                               ],
        "mainImage":  "/images/products/pumps/plunger-pump/ea/pump-ea-1000ul-peek.webp",
        "additionalImages":  [
                                 "/images/products/pumps/plunger-pump/ea/pump-ea-duanzi.webp",
                                 "/images/products/pumps/plunger-pump/ea/pump-ea-guangou.webp"
                             ],
        "showConfiguration":  true,
        "showDatasheetRequest":  true,
        "show2DRequest":  true,
        "show3DRequest":  true,
        "faqSeries":  "EA常规柱塞泵"
    },
    {
        "category":  "pumps",
        "productFamily":  "EA常规柱塞泵",
        "slug":  "ea-2500-pmma",
        "model":  "EA-2500-PMMA",
        "name":  "常规柱塞泵",
        "capacity":  2500,
        "material":  "PMMA",
        "advantages":  [
                           "精密定量输送",
                           "满量程准确度≤0.5%",
                           "满量程重复性≤0.5%",
                           "支持1/4-28 UNF或M6平底接口",
                           "适合自动化液路系统集成"
                       ],
        "commonApplications":  [
                                   "IVD诊断设备",
                                   "生命科学仪器",
                                   "实验室自动化",
                                   "分析仪器"
                               ],
        "mainImage":  "/images/products/pumps/plunger-pump/ea/pump-ea-2500ul-pmma.webp",
        "additionalImages":  [
                                 "/images/products/pumps/plunger-pump/ea/pump-ea-duanzi.webp",
                                 "/images/products/pumps/plunger-pump/ea/pump-ea-guangou.webp"
                             ],
        "showConfiguration":  true,
        "showDatasheetRequest":  true,
        "show2DRequest":  true,
        "show3DRequest":  true,
        "faqSeries":  "EA常规柱塞泵"
    },
    {
        "category":  "pumps",
        "productFamily":  "EA常规柱塞泵",
        "slug":  "ea-2500-peek",
        "model":  "EA-2500-PEEK",
        "name":  "常规柱塞泵",
        "capacity":  2500,
        "material":  "PEEK",
        "advantages":  [
                           "精密定量输送",
                           "满量程准确度≤0.5%",
                           "满量程重复性≤0.5%",
                           "支持1/4-28 UNF或M6平底接口",
                           "适合自动化液路系统集成"
                       ],
        "commonApplications":  [
                                   "IVD诊断设备",
                                   "生命科学仪器",
                                   "实验室自动化",
                                   "分析仪器"
                               ],
        "mainImage":  "/images/products/pumps/plunger-pump/ea/pump-ea-2500ul-peek.webp",
        "additionalImages":  [
                                 "/images/products/pumps/plunger-pump/ea/pump-ea-duanzi.webp",
                                 "/images/products/pumps/plunger-pump/ea/pump-ea-guangou.webp"
                             ],
        "showConfiguration":  true,
        "showDatasheetRequest":  true,
        "show2DRequest":  true,
        "show3DRequest":  true,
        "faqSeries":  "EA常规柱塞泵"
    },
    {
        "category":  "pumps",
        "productFamily":  "EA常规柱塞泵",
        "slug":  "ea-5000-pmma",
        "model":  "EA-5000-PMMA",
        "name":  "常规柱塞泵",
        "capacity":  5000,
        "material":  "PMMA",
        "advantages":  [
                           "精密定量输送",
                           "满量程准确度≤0.5%",
                           "满量程重复性≤0.5%",
                           "支持1/4-28 UNF或M6平底接口",
                           "适合自动化液路系统集成"
                       ],
        "commonApplications":  [
                                   "IVD诊断设备",
                                   "生命科学仪器",
                                   "实验室自动化",
                                   "分析仪器"
                               ],
        "mainImage":  "/images/products/pumps/plunger-pump/ea/pump-ea-5000ul-pmma.webp",
        "additionalImages":  [
                                 "/images/products/pumps/plunger-pump/ea/pump-ea-duanzi.webp",
                                 "/images/products/pumps/plunger-pump/ea/pump-ea-guangou.webp"
                             ],
        "showConfiguration":  true,
        "showDatasheetRequest":  true,
        "show2DRequest":  true,
        "show3DRequest":  true,
        "faqSeries":  "EA常规柱塞泵"
    },
    {
        "category":  "pumps",
        "productFamily":  "EA常规柱塞泵",
        "slug":  "ea-5000-peek",
        "model":  "EA-5000-PEEK",
        "name":  "常规柱塞泵",
        "capacity":  5000,
        "material":  "PEEK",
        "advantages":  [
                           "精密定量输送",
                           "满量程准确度≤0.5%",
                           "满量程重复性≤0.5%",
                           "支持1/4-28 UNF或M6平底接口",
                           "适合自动化液路系统集成"
                       ],
        "commonApplications":  [
                                   "IVD诊断设备",
                                   "生命科学仪器",
                                   "实验室自动化",
                                   "分析仪器"
                               ],
        "mainImage":  "/images/products/pumps/plunger-pump/ea/pump-ea-5000ul-peek.webp",
        "additionalImages":  [
                                 "/images/products/pumps/plunger-pump/ea/pump-ea-duanzi.webp",
                                 "/images/products/pumps/plunger-pump/ea/pump-ea-guangou.webp"
                             ],
        "showConfiguration":  true,
        "showDatasheetRequest":  true,
        "show2DRequest":  true,
        "show3DRequest":  true,
        "faqSeries":  "EA常规柱塞泵"
    },
    {
        "category":  "pumps",
        "productFamily":  "EA常规柱塞泵",
        "slug":  "ea-10000-pmma",
        "model":  "EA-10000-PMMA",
        "name":  "常规柱塞泵",
        "capacity":  10000,
        "material":  "PMMA",
        "advantages":  [
                           "精密定量输送",
                           "满量程准确度≤0.5%",
                           "满量程重复性≤0.5%",
                           "支持1/4-28 UNF或M6平底接口",
                           "适合自动化液路系统集成"
                       ],
        "commonApplications":  [
                                   "IVD诊断设备",
                                   "生命科学仪器",
                                   "实验室自动化",
                                   "分析仪器"
                               ],
        "mainImage":  "/images/products/pumps/plunger-pump/ea/pump-ea-10000ul-pmma.webp",
        "additionalImages":  [
                                 "/images/products/pumps/plunger-pump/ea/pump-ea-duanzi.webp",
                                 "/images/products/pumps/plunger-pump/ea/pump-ea-guangou.webp"
                             ],
        "showConfiguration":  true,
        "showDatasheetRequest":  true,
        "show2DRequest":  true,
        "show3DRequest":  true,
        "faqSeries":  "EA常规柱塞泵"
    },
    {
        "category":  "pumps",
        "productFamily":  "EA常规柱塞泵",
        "slug":  "ea-10000-peek",
        "model":  "EA-10000-PEEK",
        "name":  "常规柱塞泵",
        "capacity":  10000,
        "material":  "PEEK",
        "advantages":  [
                           "精密定量输送",
                           "满量程准确度≤0.5%",
                           "满量程重复性≤0.5%",
                           "支持1/4-28 UNF或M6平底接口",
                           "适合自动化液路系统集成"
                       ],
        "commonApplications":  [
                                   "IVD诊断设备",
                                   "生命科学仪器",
                                   "实验室自动化",
                                   "分析仪器"
                               ],
        "mainImage":  "/images/products/pumps/plunger-pump/ea/pump-ea-10000ul-peek.webp",
        "additionalImages":  [
                                 "/images/products/pumps/plunger-pump/ea/pump-ea-duanzi.webp",
                                 "/images/products/pumps/plunger-pump/ea/pump-ea-guangou.webp"
                             ],
        "showConfiguration":  true,
        "showDatasheetRequest":  true,
        "show2DRequest":  true,
        "show3DRequest":  true,
        "faqSeries":  "EA常规柱塞泵"
    }
] as EaProductDetailZh[];

export const eaProductDetailZhBySlug: Record<string, EaProductDetailZh> =
  Object.fromEntries(
    eaProductDetailsZh.map((item) => [item.slug, item]),
  );

export const eaProductDetailStaticParams = eaProductDetailsZh.map(
  (item) => ({
    category: item.category,
    slug: item.slug,
  }),
);

export function getEaProductDetailZhBySlug(
  slug: string,
): EaProductDetailZh | null {
  return eaProductDetailZhBySlug[slug.toLowerCase()] ?? null;
}