/* =========================================================
   AUTO-GENERATED FILE — DO NOT EDIT MANUALLY

   Source:
   data-source/product-center/pumps/plunger-pump/ea/
   02_EA常规柱塞泵_规格参数_zh.xlsx

   Generated by:
   generate_ea_product_detail_data_v3_excel_com_utf8bom.ps1
========================================================= */

export type EaProductSpecRow = {
  name: string;
  value: string;
};

export const eaProductSpecsZhBySlug = {
    "ea-10000-peek":  [
                          {
                              "name":  "页面 slug",
                              "value":  "ea-10000-peek"
                          },
                          {
                              "name":  "型号",
                              "value":  "EA-10000-PEEK"
                          },
                          {
                              "name":  "名称",
                              "value":  "常规柱塞泵"
                          },
                          {
                              "name":  "容量",
                              "value":  "10000 μL"
                          },
                          {
                              "name":  "泵头材质",
                              "value":  "PEEK"
                          },
                          {
                              "name":  "系列代号",
                              "value":  "EA-C"
                          },
                          {
                              "name":  "分辨率",
                              "value":  "2.5 μL / 步"
                          },
                          {
                              "name":  "全行程步数",
                              "value":  "4000 步"
                          },
                          {
                              "name":  "螺距",
                              "value":  "1.27 mm"
                          },
                          {
                              "name":  "泵类型",
                              "value":  "柱塞式"
                          },
                          {
                              "name":  "柱塞材质",
                              "value":  "陶瓷"
                          },
                          {
                              "name":  "安装尺寸",
                              "value":  "2×M3×31.8 或 2×M3×42.8"
                          },
                          {
                              "name":  "接口",
                              "value":  "2×1/4-28 UNF 或 2×M6，平底接口"
                          },
                          {
                              "name":  "回程差",
                              "value":  "≤1.0%"
                          },
                          {
                              "name":  "满量程准确度",
                              "value":  "≤0.5%"
                          },
                          {
                              "name":  "满量程重复性",
                              "value":  "≤0.5%"
                          },
                          {
                              "name":  "2%量程准确度",
                              "value":  "≤2.0%"
                          },
                          {
                              "name":  "2%量程重复性",
                              "value":  "≤1.5%"
                          },
                          {
                              "name":  "流体压力",
                              "value":  "\u003c0.30 MPa"
                          }
                      ],
    "ea-10000-pmma":  [
                          {
                              "name":  "页面 slug",
                              "value":  "ea-10000-pmma"
                          },
                          {
                              "name":  "型号",
                              "value":  "EA-10000-PMMA"
                          },
                          {
                              "name":  "名称",
                              "value":  "常规柱塞泵"
                          },
                          {
                              "name":  "容量",
                              "value":  "10000 μL"
                          },
                          {
                              "name":  "泵头材质",
                              "value":  "PMMA"
                          },
                          {
                              "name":  "系列代号",
                              "value":  "EA-C"
                          },
                          {
                              "name":  "分辨率",
                              "value":  "2.5 μL / 步"
                          },
                          {
                              "name":  "全行程步数",
                              "value":  "4000 步"
                          },
                          {
                              "name":  "螺距",
                              "value":  "1.27 mm"
                          },
                          {
                              "name":  "泵类型",
                              "value":  "柱塞式"
                          },
                          {
                              "name":  "柱塞材质",
                              "value":  "陶瓷"
                          },
                          {
                              "name":  "安装尺寸",
                              "value":  "2×M3×31.8 或 2×M3×42.8"
                          },
                          {
                              "name":  "接口",
                              "value":  "2×1/4-28 UNF 或 2×M6，平底接口"
                          },
                          {
                              "name":  "回程差",
                              "value":  "≤1.0%"
                          },
                          {
                              "name":  "满量程准确度",
                              "value":  "≤0.5%"
                          },
                          {
                              "name":  "满量程重复性",
                              "value":  "≤0.5%"
                          },
                          {
                              "name":  "2%量程准确度",
                              "value":  "≤2.0%"
                          },
                          {
                              "name":  "2%量程重复性",
                              "value":  "≤1.5%"
                          },
                          {
                              "name":  "流体压力",
                              "value":  "\u003c0.30 MPa"
                          }
                      ],
    "ea-1000-peek":  [
                         {
                             "name":  "页面 slug",
                             "value":  "ea-1000-peek"
                         },
                         {
                             "name":  "型号",
                             "value":  "EA-1000-PEEK"
                         },
                         {
                             "name":  "名称",
                             "value":  "常规柱塞泵"
                         },
                         {
                             "name":  "容量",
                             "value":  "1000 μL"
                         },
                         {
                             "name":  "泵头材质",
                             "value":  "PEEK"
                         },
                         {
                             "name":  "系列代号",
                             "value":  "EA-5"
                         },
                         {
                             "name":  "分辨率",
                             "value":  "0.5 μL / 步"
                         },
                         {
                             "name":  "全行程步数",
                             "value":  "2000 步"
                         },
                         {
                             "name":  "螺距",
                             "value":  "1.27 mm"
                         },
                         {
                             "name":  "泵类型",
                             "value":  "柱塞式"
                         },
                         {
                             "name":  "柱塞材质",
                             "value":  "陶瓷"
                         },
                         {
                             "name":  "安装尺寸",
                             "value":  "2×M3×31.8 或 2×M3×42.8"
                         },
                         {
                             "name":  "接口",
                             "value":  "2×1/4-28 UNF 或 2×M6，平底接口"
                         },
                         {
                             "name":  "回程差",
                             "value":  "≤1.0%"
                         },
                         {
                             "name":  "满量程准确度",
                             "value":  "≤0.5%"
                         },
                         {
                             "name":  "满量程重复性",
                             "value":  "≤0.5%"
                         },
                         {
                             "name":  "2%量程准确度",
                             "value":  "≤2.0%"
                         },
                         {
                             "name":  "2%量程重复性",
                             "value":  "≤1.5%"
                         },
                         {
                             "name":  "流体压力",
                             "value":  "\u003c0.30 MPa"
                         }
                     ],
    "ea-1000-pmma":  [
                         {
                             "name":  "页面 slug",
                             "value":  "ea-1000-pmma"
                         },
                         {
                             "name":  "型号",
                             "value":  "EA-1000-PMMA"
                         },
                         {
                             "name":  "名称",
                             "value":  "常规柱塞泵"
                         },
                         {
                             "name":  "容量",
                             "value":  "1000 μL"
                         },
                         {
                             "name":  "泵头材质",
                             "value":  "PMMA"
                         },
                         {
                             "name":  "系列代号",
                             "value":  "EA-5"
                         },
                         {
                             "name":  "分辨率",
                             "value":  "0.5 μL / 步"
                         },
                         {
                             "name":  "全行程步数",
                             "value":  "2000 步"
                         },
                         {
                             "name":  "螺距",
                             "value":  "1.27 mm"
                         },
                         {
                             "name":  "泵类型",
                             "value":  "柱塞式"
                         },
                         {
                             "name":  "柱塞材质",
                             "value":  "陶瓷"
                         },
                         {
                             "name":  "安装尺寸",
                             "value":  "2×M3×31.8 或 2×M3×42.8"
                         },
                         {
                             "name":  "接口",
                             "value":  "2×1/4-28 UNF 或 2×M6，平底接口"
                         },
                         {
                             "name":  "回程差",
                             "value":  "≤1.0%"
                         },
                         {
                             "name":  "满量程准确度",
                             "value":  "≤0.5%"
                         },
                         {
                             "name":  "满量程重复性",
                             "value":  "≤0.5%"
                         },
                         {
                             "name":  "2%量程准确度",
                             "value":  "≤2.0%"
                         },
                         {
                             "name":  "2%量程重复性",
                             "value":  "≤1.5%"
                         },
                         {
                             "name":  "流体压力",
                             "value":  "\u003c0.30 MPa"
                         }
                     ],
    "ea-100-peek":  [
                        {
                            "name":  "页面 slug",
                            "value":  "ea-100-peek"
                        },
                        {
                            "name":  "型号",
                            "value":  "EA-100-PEEK"
                        },
                        {
                            "name":  "名称",
                            "value":  "常规柱塞泵"
                        },
                        {
                            "name":  "容量",
                            "value":  "100 μL"
                        },
                        {
                            "name":  "泵头材质",
                            "value":  "PEEK"
                        },
                        {
                            "name":  "系列代号",
                            "value":  "EA-2"
                        },
                        {
                            "name":  "分辨率",
                            "value":  "0.05 μL / 步"
                        },
                        {
                            "name":  "全行程步数",
                            "value":  "2000 步"
                        },
                        {
                            "name":  "螺距",
                            "value":  "1.27 mm"
                        },
                        {
                            "name":  "泵类型",
                            "value":  "柱塞式"
                        },
                        {
                            "name":  "柱塞材质",
                            "value":  "陶瓷"
                        },
                        {
                            "name":  "安装尺寸",
                            "value":  "2×M3×31.8 或 2×M3×42.8"
                        },
                        {
                            "name":  "接口",
                            "value":  "2×1/4-28 UNF 或 2×M6，平底接口"
                        },
                        {
                            "name":  "回程差",
                            "value":  "≤1.0%"
                        },
                        {
                            "name":  "满量程准确度",
                            "value":  "≤0.5%"
                        },
                        {
                            "name":  "满量程重复性",
                            "value":  "≤0.5%"
                        },
                        {
                            "name":  "2%量程准确度",
                            "value":  "≤2.0%"
                        },
                        {
                            "name":  "2%量程重复性",
                            "value":  "≤1.5%"
                        },
                        {
                            "name":  "流体压力",
                            "value":  "\u003c0.30 MPa"
                        }
                    ],
    "ea-100-pmma":  [
                        {
                            "name":  "页面 slug",
                            "value":  "ea-100-pmma"
                        },
                        {
                            "name":  "型号",
                            "value":  "EA-100-PMMA"
                        },
                        {
                            "name":  "名称",
                            "value":  "常规柱塞泵"
                        },
                        {
                            "name":  "容量",
                            "value":  "100 μL"
                        },
                        {
                            "name":  "泵头材质",
                            "value":  "PMMA"
                        },
                        {
                            "name":  "系列代号",
                            "value":  "EA-2"
                        },
                        {
                            "name":  "分辨率",
                            "value":  "0.05 μL / 步"
                        },
                        {
                            "name":  "全行程步数",
                            "value":  "2000 步"
                        },
                        {
                            "name":  "螺距",
                            "value":  "1.27 mm"
                        },
                        {
                            "name":  "泵类型",
                            "value":  "柱塞式"
                        },
                        {
                            "name":  "柱塞材质",
                            "value":  "陶瓷"
                        },
                        {
                            "name":  "安装尺寸",
                            "value":  "2×M3×31.8 或 2×M3×42.8"
                        },
                        {
                            "name":  "接口",
                            "value":  "2×1/4-28 UNF 或 2×M6，平底接口"
                        },
                        {
                            "name":  "回程差",
                            "value":  "≤1.0%"
                        },
                        {
                            "name":  "满量程准确度",
                            "value":  "≤0.5%"
                        },
                        {
                            "name":  "满量程重复性",
                            "value":  "≤0.5%"
                        },
                        {
                            "name":  "2%量程准确度",
                            "value":  "≤2.0%"
                        },
                        {
                            "name":  "2%量程重复性",
                            "value":  "≤1.5%"
                        },
                        {
                            "name":  "流体压力",
                            "value":  "\u003c0.30 MPa"
                        }
                    ],
    "ea-2500-peek":  [
                         {
                             "name":  "页面 slug",
                             "value":  "ea-2500-peek"
                         },
                         {
                             "name":  "型号",
                             "value":  "EA-2500-PEEK"
                         },
                         {
                             "name":  "名称",
                             "value":  "常规柱塞泵"
                         },
                         {
                             "name":  "容量",
                             "value":  "2500 μL"
                         },
                         {
                             "name":  "泵头材质",
                             "value":  "PEEK"
                         },
                         {
                             "name":  "系列代号",
                             "value":  "EA-6"
                         },
                         {
                             "name":  "分辨率",
                             "value":  "1.12 μL / 步"
                         },
                         {
                             "name":  "全行程步数",
                             "value":  "2236 步"
                         },
                         {
                             "name":  "螺距",
                             "value":  "1.27 mm"
                         },
                         {
                             "name":  "泵类型",
                             "value":  "柱塞式"
                         },
                         {
                             "name":  "柱塞材质",
                             "value":  "陶瓷"
                         },
                         {
                             "name":  "安装尺寸",
                             "value":  "2×M3×31.8 或 2×M3×42.8"
                         },
                         {
                             "name":  "接口",
                             "value":  "2×1/4-28 UNF 或 2×M6，平底接口"
                         },
                         {
                             "name":  "回程差",
                             "value":  "≤1.0%"
                         },
                         {
                             "name":  "满量程准确度",
                             "value":  "≤0.5%"
                         },
                         {
                             "name":  "满量程重复性",
                             "value":  "≤0.5%"
                         },
                         {
                             "name":  "2%量程准确度",
                             "value":  "≤2.0%"
                         },
                         {
                             "name":  "2%量程重复性",
                             "value":  "≤1.5%"
                         },
                         {
                             "name":  "流体压力",
                             "value":  "\u003c0.30 MPa"
                         }
                     ],
    "ea-2500-pmma":  [
                         {
                             "name":  "页面 slug",
                             "value":  "ea-2500-pmma"
                         },
                         {
                             "name":  "型号",
                             "value":  "EA-2500-PMMA"
                         },
                         {
                             "name":  "名称",
                             "value":  "常规柱塞泵"
                         },
                         {
                             "name":  "容量",
                             "value":  "2500 μL"
                         },
                         {
                             "name":  "泵头材质",
                             "value":  "PMMA"
                         },
                         {
                             "name":  "系列代号",
                             "value":  "EA-6"
                         },
                         {
                             "name":  "分辨率",
                             "value":  "1.12 μL / 步"
                         },
                         {
                             "name":  "全行程步数",
                             "value":  "2236 步"
                         },
                         {
                             "name":  "螺距",
                             "value":  "1.27 mm"
                         },
                         {
                             "name":  "泵类型",
                             "value":  "柱塞式"
                         },
                         {
                             "name":  "柱塞材质",
                             "value":  "陶瓷"
                         },
                         {
                             "name":  "安装尺寸",
                             "value":  "2×M3×31.8 或 2×M3×42.8"
                         },
                         {
                             "name":  "接口",
                             "value":  "2×1/4-28 UNF 或 2×M6，平底接口"
                         },
                         {
                             "name":  "回程差",
                             "value":  "≤1.0%"
                         },
                         {
                             "name":  "满量程准确度",
                             "value":  "≤0.5%"
                         },
                         {
                             "name":  "满量程重复性",
                             "value":  "≤0.5%"
                         },
                         {
                             "name":  "2%量程准确度",
                             "value":  "≤2.0%"
                         },
                         {
                             "name":  "2%量程重复性",
                             "value":  "≤1.5%"
                         },
                         {
                             "name":  "流体压力",
                             "value":  "\u003c0.30 MPa"
                         }
                     ],
    "ea-250-peek":  [
                        {
                            "name":  "页面 slug",
                            "value":  "ea-250-peek"
                        },
                        {
                            "name":  "型号",
                            "value":  "EA-250-PEEK"
                        },
                        {
                            "name":  "名称",
                            "value":  "常规柱塞泵"
                        },
                        {
                            "name":  "容量",
                            "value":  "250 μL"
                        },
                        {
                            "name":  "泵头材质",
                            "value":  "PEEK"
                        },
                        {
                            "name":  "系列代号",
                            "value":  "EA-3"
                        },
                        {
                            "name":  "分辨率",
                            "value":  "0.125 μL / 步"
                        },
                        {
                            "name":  "全行程步数",
                            "value":  "2000 步"
                        },
                        {
                            "name":  "螺距",
                            "value":  "1.27 mm"
                        },
                        {
                            "name":  "泵类型",
                            "value":  "柱塞式"
                        },
                        {
                            "name":  "柱塞材质",
                            "value":  "陶瓷"
                        },
                        {
                            "name":  "安装尺寸",
                            "value":  "2×M3×31.8 或 2×M3×42.8"
                        },
                        {
                            "name":  "接口",
                            "value":  "2×1/4-28 UNF 或 2×M6，平底接口"
                        },
                        {
                            "name":  "回程差",
                            "value":  "≤1.0%"
                        },
                        {
                            "name":  "满量程准确度",
                            "value":  "≤0.5%"
                        },
                        {
                            "name":  "满量程重复性",
                            "value":  "≤0.5%"
                        },
                        {
                            "name":  "2%量程准确度",
                            "value":  "≤2.0%"
                        },
                        {
                            "name":  "2%量程重复性",
                            "value":  "≤1.5%"
                        },
                        {
                            "name":  "流体压力",
                            "value":  "\u003c0.30 MPa"
                        }
                    ],
    "ea-250-pmma":  [
                        {
                            "name":  "页面 slug",
                            "value":  "ea-250-pmma"
                        },
                        {
                            "name":  "型号",
                            "value":  "EA-250-PMMA"
                        },
                        {
                            "name":  "名称",
                            "value":  "常规柱塞泵"
                        },
                        {
                            "name":  "容量",
                            "value":  "250 μL"
                        },
                        {
                            "name":  "泵头材质",
                            "value":  "PMMA"
                        },
                        {
                            "name":  "系列代号",
                            "value":  "EA-3"
                        },
                        {
                            "name":  "分辨率",
                            "value":  "0.125 μL / 步"
                        },
                        {
                            "name":  "全行程步数",
                            "value":  "2000 步"
                        },
                        {
                            "name":  "螺距",
                            "value":  "1.27 mm"
                        },
                        {
                            "name":  "泵类型",
                            "value":  "柱塞式"
                        },
                        {
                            "name":  "柱塞材质",
                            "value":  "陶瓷"
                        },
                        {
                            "name":  "安装尺寸",
                            "value":  "2×M3×31.8 或 2×M3×42.8"
                        },
                        {
                            "name":  "接口",
                            "value":  "2×1/4-28 UNF 或 2×M6，平底接口"
                        },
                        {
                            "name":  "回程差",
                            "value":  "≤1.0%"
                        },
                        {
                            "name":  "满量程准确度",
                            "value":  "≤0.5%"
                        },
                        {
                            "name":  "满量程重复性",
                            "value":  "≤0.5%"
                        },
                        {
                            "name":  "2%量程准确度",
                            "value":  "≤2.0%"
                        },
                        {
                            "name":  "2%量程重复性",
                            "value":  "≤1.5%"
                        },
                        {
                            "name":  "流体压力",
                            "value":  "\u003c0.30 MPa"
                        }
                    ],
    "ea-5000-peek":  [
                         {
                             "name":  "页面 slug",
                             "value":  "ea-5000-peek"
                         },
                         {
                             "name":  "型号",
                             "value":  "EA-5000-PEEK"
                         },
                         {
                             "name":  "名称",
                             "value":  "常规柱塞泵"
                         },
                         {
                             "name":  "容量",
                             "value":  "5000 μL"
                         },
                         {
                             "name":  "泵头材质",
                             "value":  "PEEK"
                         },
                         {
                             "name":  "系列代号",
                             "value":  "EA-7"
                         },
                         {
                             "name":  "分辨率",
                             "value":  "2.5 μL / 步"
                         },
                         {
                             "name":  "全行程步数",
                             "value":  "2000 步"
                         },
                         {
                             "name":  "螺距",
                             "value":  "1.27 mm"
                         },
                         {
                             "name":  "泵类型",
                             "value":  "柱塞式"
                         },
                         {
                             "name":  "柱塞材质",
                             "value":  "陶瓷"
                         },
                         {
                             "name":  "安装尺寸",
                             "value":  "2×M3×31.8 或 2×M3×42.8"
                         },
                         {
                             "name":  "接口",
                             "value":  "2×1/4-28 UNF 或 2×M6，平底接口"
                         },
                         {
                             "name":  "回程差",
                             "value":  "≤1.0%"
                         },
                         {
                             "name":  "满量程准确度",
                             "value":  "≤0.5%"
                         },
                         {
                             "name":  "满量程重复性",
                             "value":  "≤0.5%"
                         },
                         {
                             "name":  "2%量程准确度",
                             "value":  "≤2.0%"
                         },
                         {
                             "name":  "2%量程重复性",
                             "value":  "≤1.5%"
                         },
                         {
                             "name":  "流体压力",
                             "value":  "\u003c0.30 MPa"
                         }
                     ],
    "ea-5000-pmma":  [
                         {
                             "name":  "页面 slug",
                             "value":  "ea-5000-pmma"
                         },
                         {
                             "name":  "型号",
                             "value":  "EA-5000-PMMA"
                         },
                         {
                             "name":  "名称",
                             "value":  "常规柱塞泵"
                         },
                         {
                             "name":  "容量",
                             "value":  "5000 μL"
                         },
                         {
                             "name":  "泵头材质",
                             "value":  "PMMA"
                         },
                         {
                             "name":  "系列代号",
                             "value":  "EA-7"
                         },
                         {
                             "name":  "分辨率",
                             "value":  "2.5 μL / 步"
                         },
                         {
                             "name":  "全行程步数",
                             "value":  "2000 步"
                         },
                         {
                             "name":  "螺距",
                             "value":  "1.27 mm"
                         },
                         {
                             "name":  "泵类型",
                             "value":  "柱塞式"
                         },
                         {
                             "name":  "柱塞材质",
                             "value":  "陶瓷"
                         },
                         {
                             "name":  "安装尺寸",
                             "value":  "2×M3×31.8 或 2×M3×42.8"
                         },
                         {
                             "name":  "接口",
                             "value":  "2×1/4-28 UNF 或 2×M6，平底接口"
                         },
                         {
                             "name":  "回程差",
                             "value":  "≤1.0%"
                         },
                         {
                             "name":  "满量程准确度",
                             "value":  "≤0.5%"
                         },
                         {
                             "name":  "满量程重复性",
                             "value":  "≤0.5%"
                         },
                         {
                             "name":  "2%量程准确度",
                             "value":  "≤2.0%"
                         },
                         {
                             "name":  "2%量程重复性",
                             "value":  "≤1.5%"
                         },
                         {
                             "name":  "流体压力",
                             "value":  "\u003c0.30 MPa"
                         }
                     ],
    "ea-500-peek":  [
                        {
                            "name":  "页面 slug",
                            "value":  "ea-500-peek"
                        },
                        {
                            "name":  "型号",
                            "value":  "EA-500-PEEK"
                        },
                        {
                            "name":  "名称",
                            "value":  "常规柱塞泵"
                        },
                        {
                            "name":  "容量",
                            "value":  "500 μL"
                        },
                        {
                            "name":  "泵头材质",
                            "value":  "PEEK"
                        },
                        {
                            "name":  "系列代号",
                            "value":  "EA-4"
                        },
                        {
                            "name":  "分辨率",
                            "value":  "0.25 μL / 步"
                        },
                        {
                            "name":  "全行程步数",
                            "value":  "2000 步"
                        },
                        {
                            "name":  "螺距",
                            "value":  "1.27 mm"
                        },
                        {
                            "name":  "泵类型",
                            "value":  "柱塞式"
                        },
                        {
                            "name":  "柱塞材质",
                            "value":  "陶瓷"
                        },
                        {
                            "name":  "安装尺寸",
                            "value":  "2×M3×31.8 或 2×M3×42.8"
                        },
                        {
                            "name":  "接口",
                            "value":  "2×1/4-28 UNF 或 2×M6，平底接口"
                        },
                        {
                            "name":  "回程差",
                            "value":  "≤1.0%"
                        },
                        {
                            "name":  "满量程准确度",
                            "value":  "≤0.5%"
                        },
                        {
                            "name":  "满量程重复性",
                            "value":  "≤0.5%"
                        },
                        {
                            "name":  "2%量程准确度",
                            "value":  "≤2.0%"
                        },
                        {
                            "name":  "2%量程重复性",
                            "value":  "≤1.5%"
                        },
                        {
                            "name":  "流体压力",
                            "value":  "\u003c0.30 MPa"
                        }
                    ],
    "ea-500-pmma":  [
                        {
                            "name":  "页面 slug",
                            "value":  "ea-500-pmma"
                        },
                        {
                            "name":  "型号",
                            "value":  "EA-500-PMMA"
                        },
                        {
                            "name":  "名称",
                            "value":  "常规柱塞泵"
                        },
                        {
                            "name":  "容量",
                            "value":  "500 μL"
                        },
                        {
                            "name":  "泵头材质",
                            "value":  "PMMA"
                        },
                        {
                            "name":  "系列代号",
                            "value":  "EA-4"
                        },
                        {
                            "name":  "分辨率",
                            "value":  "0.25 μL / 步"
                        },
                        {
                            "name":  "全行程步数",
                            "value":  "2000 步"
                        },
                        {
                            "name":  "螺距",
                            "value":  "1.27 mm"
                        },
                        {
                            "name":  "泵类型",
                            "value":  "柱塞式"
                        },
                        {
                            "name":  "柱塞材质",
                            "value":  "陶瓷"
                        },
                        {
                            "name":  "安装尺寸",
                            "value":  "2×M3×31.8 或 2×M3×42.8"
                        },
                        {
                            "name":  "接口",
                            "value":  "2×1/4-28 UNF 或 2×M6，平底接口"
                        },
                        {
                            "name":  "回程差",
                            "value":  "≤1.0%"
                        },
                        {
                            "name":  "满量程准确度",
                            "value":  "≤0.5%"
                        },
                        {
                            "name":  "满量程重复性",
                            "value":  "≤0.5%"
                        },
                        {
                            "name":  "2%量程准确度",
                            "value":  "≤2.0%"
                        },
                        {
                            "name":  "2%量程重复性",
                            "value":  "≤1.5%"
                        },
                        {
                            "name":  "流体压力",
                            "value":  "\u003c0.30 MPa"
                        }
                    ]
} as Record<
  string,
  EaProductSpecRow[]
>;

export function getEaProductSpecsZhBySlug(
  slug: string,
): EaProductSpecRow[] {
  return eaProductSpecsZhBySlug[slug.toLowerCase()] ?? [];
}